### ISSUE TITLE
Missing up metrics

### ISSUE THREAD

**Issue by voanhduy1512** [kubernetes-monitoring/kubernetes-mixin#106]
Hi,

I am trying to setup prometheus alert using this but found a problem that prometheus doesn't have metric `up{job="kube-controller-manager"}`. As my understanding, this is a config in prometheus to scrape `kube-controller-manager`.

So my question is: do i need any special setup on prometheus? Right now i use the default setup from prometheus helm chart https://github.com/helm/charts/blob/8ac01b83b5fd992600928d1e2ff159f69b64b484/stable/prometheus/values.yaml#L810.

Thanks

**Comment by metalmatze** [comment]
Some cloud providers don't expose their controller manager and scheduler to the customers and therefore you're unable to scrape.
We have a separate issue to not alert on these control-plane components: https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/50

The helm chart you have linked does not use these mixins. I'm not sure why you have created an issue here.

**Comment by voanhduy1512** [comment]
Because I didn't see any special requirements on the readme so i thought this mixin is unopinionted and works on most of standard prometheus setup. Sorry for the misunderstanding.
Before i close the issue, can i ask what is the configuration required for prometheus for this mixin to work? I deploy k8s using kops on AWS.

Thanks

**Comment by metalmatze** [comment]
You're correct. If you want to use the mixins you can use them. They simply don't ship with the helm chart you referenced. So it was me misunderstanding if you did add these on your own.

I'm not exactly sure what needs to be changed for AWS, probably the job selectors as they are different for most people.

**Comment by voanhduy1512** [comment]
I need to config prometheus which correct job name and label keys and stuffs, but that's all good now. Thanks
