### ISSUE TITLE
Storage specific panels under k8s/Compute Resources/Cluster

### ISSUE THREAD

**Issue by shtripat** [kubernetes-monitoring/kubernetes-mixin#122]
Currently there are no storage specific metrics displayed under any of the k8s dashboards. This issue is being raised to incorporate storage specific panels under `k8s/Compute Resource/Cluster`. The proposed changes are attached for reference here.

![screenshot from 2018-11-27 19-33-34](https://user-images.githubusercontent.com/6771252/49086801-68ec0e80-f27b-11e8-9944-f5b921a67173.png)

**Comment by cloudbehl** [comment]
Dependent on: https://github.com/kubernetes/kubernetes/issues/69507
