### ISSUE TITLE
"mapping values are not allowed in this context" error from promtool

### ISSUE THREAD

**Issue by adamdecaf** [kubernetes-monitoring/kubernetes-mixin#14]
I was running [promtool](https://github.com/prometheus/prometheus/tree/master/cmd/promtool) over the generated rule files and ran into the following. This is likely a bug in jsonnet's yaml generation, but do you have any thoughts? 

Note the `'`'s around the `record:` value. 

```
$ cat /tmp/mapping.rules.yaml 
groups:
  - name: "node.rules"
    rules:
      - record: ':kube_pod_info_node_count:'
        expr: sum(min by(node) (kube_pod_info))

$ promtool check rules /tmp/mapping.rules.yaml 
Checking /tmp/mapping.rules.yaml
  SUCCESS: 1 rules found
```

```
$ cat /tmp/mapping-bad.rules.yaml 
groups:
  - name: "node.rules"
    rules:
      - record: :kube_pod_info_node_count:
        expr: sum(min by(node) (kube_pod_info))

$ promtool check rules /tmp/mapping-bad.rules.yaml 
Checking /tmp/mapping-bad.rules.yaml
  FAILED:
yaml: line 3: mapping values are not allowed in this context
```

**Comment by tomwilkie** [comment]
Hi Adam - what version of jsonnet are you using?  Does `make lint` also fail?

We use jsonnet 0.10 in the CI and it works...

**Comment by adamdecaf** [comment]
I'm on the same jsonnet version.

```
$ jsonnet -version
Jsonnet commandline interpreter v0.10.0
```

```
$ make lint
jsonnet -S lib/alerts.jsonnet > prometheus_alerts.yaml
find . -name 'vendor' -prune -o -name '*.libsonnet' -print -o -name '*.jsonnet' -print | \
		while read f; do \
			jsonnet fmt -n 2 --max-blank-lines 2 --string-style s --comment-style s "$f" | diff -u "$f" -; \
		done
promtool check rules prometheus_rules.yaml
Checking prometheus_rules.yaml
  SUCCESS: 29 rules found

promtool check rules prometheus_alerts.yaml
Checking prometheus_alerts.yaml
  SUCCESS: 15 rules found
```

The generated yaml has quotes around it, so maybe this was my fault. 

```
- "expr": |
      sum(irate(node_network_receive_drop{job="default/node-exporter",device="eth0"}[1m])) +
      sum(irate(node_network_transmit_drop{job="default/node-exporter",device="eth0"}[1m]))
    "record": ":node_net_saturation:sum_irate"
```

**Comment by tomwilkie** [comment]
Weird, would be good to get to the bottom of what happened.  Perhaps the original set was generated with a different version of jsonnet?   Feel free to close if you can't reproduce.

**Comment by adamdecaf** [comment]
Oh. I know the issue.

These rules are vendored into [coreos/prometheus-operator](https://raw.githubusercontent.com/coreos/prometheus-operator/master/contrib/kube-prometheus/manifests/prometheus-rules.yaml), which is what I'm using. To make some edits locally I rewrote that `ConfigMap` from the `/rules` html, which doesn't quote the recording rules.

<img width="998" alt="screen shot 2018-05-11 at 8 43 25 am" src="https://user-images.githubusercontent.com/120951/39927309-66572a5a-54f7-11e8-90c8-4234966931d8.png">

Copying the above will throw this error.

**Comment by adamdecaf** [comment]
I'm going to see what the prometheus folks say. https://github.com/prometheus/prometheus/issues/4158
