### ISSUE TITLE
KubeAPIErrorsHigh flapping

### ISSUE THREAD

**Issue by cbeneke** [kubernetes-monitoring/kubernetes-mixin#146]
The alert `KubeAPIErrorsHigh` jumps quite often to 100% for us, even though the error count is quite small. There seems to be a label mismatch between 5xx and 2xx return codes (compare screenshot) and the alert does not ignore the code label. Thus everytime an error happens this will jump to 100% for us:
![screenshot 2019-01-28 at 19 24 25](https://user-images.githubusercontent.com/222009/51857455-982e0300-2332-11e9-88aa-bc3ce39b5931.png)

In this example the alerting jumped to 100% errors, even though the actual error percentage was <1%

**Comment by eyalzek** [comment]
Seeing the same behavior
