### ISSUE TITLE
 Grafana dashboard "K8s / Compute Resources / Pod" should report real memory usage without cache

### ISSUE THREAD

**Issue by onitake** [kubernetes-monitoring/kubernetes-mixin#152]
**What did you do?**
Deployed prometheus-operator including the built-in Grafana instance and the example dashboards.

**What did you expect to see?**
Useful memory metrics to monitor, debug and tune pod memory usage.

**What did you see instead? Under which circumstances?**
Pod memory is reported including caches, which can go up and down with available system memory and is not useful at all for the mentioned purposes.

The pod memory graph should clearly separate between memory that the pod uses and memory that can be reclaimed at any time. This is particularly relevant, as there is also a metric in the dashboard that counts use versus limit. This metric will be mostly useless for deployment tuning, unless cache memory is subtracted first.

It would be best if the graph and/or memory quota table below clearly separate total usage from cache, perhaps with a stacked graph. At the very least, it should be made clear that the shown `container_memory_usage_bytes` metric also includes `container_memory_cache`, similar to how the Linux command `free` reports buffer/cache and freely available memory seprately.

It was also suggested that `container_memory_rss` be used, but I think `usage` - `cache` is what's relevant for limits.

**Environment**

* Prometheus Operator version:

```
v2.5.0
```

**Comment by brancz** [comment]
I think showing all 3 lines would be best: usage, usage-cache (maybe there is a better name for it), rss.

**Comment by brancz** [comment]
Happy to review and accept a PR if you include a screenshot of before/after! :slightly_smiling_face:

**Comment by onitake** [comment]
Here's a quick test:
![image](https://user-images.githubusercontent.com/371687/52224708-f44fd480-28a8-11e9-8cee-cb989a2b8525.png)

From top to bottom:
- container_memory_usage_bytes
- container_memory_usage_bytes - container_memory_cache
- container_memory_rss
- container_memory_swap

This clearly shows that container_memory_rss is identical to container_memory_usage_bytes - container_memory_cache - if no swapping occurs and there is no "hidden" kernel memory associated with the process.
I'm not sure how relevant swap space is in the context of Kubernetes - probably something to be avoided at all cost?

**Comment by brancz** [comment]
Just thinking out loud, why don't we have one graph that has `container_memory_rss`, `container_memory_cache` and `container_memory_swap` as a stacked graph? /cc @tomwilkie @gouthamve

**Comment by onitake** [comment]
I was reluctant to do that for fear of clutter, but it doesn't look half bad.

And I also replaced the percentage base with `memory_used_bytes`, as it was before. If you add table columns with the memory breakdown, it does make a lot more sense. It's important that the user can see what kind of memory a container is using, and the percentage of actually used memory *does* include cache. It's just that the kernel can release that memory if more RSS is required.

A screenshot of the result is here: 
![image](https://user-images.githubusercontent.com/371687/52493440-bb2aa380-2bcb-11e9-89d1-39372dae2d9f.png)
And the generating JSON is here: https://gist.github.com/onitake/b8e28d2afbffe2e396c506f766466d5c

**Comment by brancz** [comment]
Nice! That looks really good I think!

**Comment by rca0** [comment]
It's great! nice job!

**Comment by onitake** [comment]
Here's a PR that applies the proposed changes to the pod and namespace dashboards.

I wonder if it makes sense for the namespace memory graph, though. It looks much more cluttered:
![image](https://user-images.githubusercontent.com/371687/52582060-97b26380-2e2c-11e9-9960-a2d4bd158994.png)

**Comment by onitake** [comment]
PR #160 was merged with the proposed changes, I'm closing this issue now.
Thanks for your valuable input!

**Comment by brancz** [comment]
Thanks a lot for the hard work, I think it's a really awesome improvement!
