### ISSUE TITLE
Missing steps to build the jsonnet-bundler

### ISSUE THREAD

**Issue by sachinmsft** [kubernetes-monitoring/kubernetes-mixin#155]
README.md file does not mention that we need to build the jsonnet-bundler to generate the jb executable before executing **jb install** command.

**Comment by metalmatze** [comment]
The README says that you should `go get github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb` which does not only clone the source code into your `$GOPATH` but also compiles a binary into `$GOPATH/bin`.
You need to have `$GOPATH/bin` in your `$PATH`.

**Comment by sachinmsft** [comment]
thanks @metalmatze. $PATH was not set properly on my machine. I am closing it.
