### ISSUE TITLE
Windows dashboards

### ISSUE THREAD

**Issue by SubodhBhargava** [kubernetes-monitoring/kubernetes-mixin#157]
There's a need to collect metrics from Windows nodes when they are added to a K8s cluster.

Node exporter and cAdvisor do not work on Windows, so we need to find alternatives to fetch Windows node and container metrics.

WMI exporter is a Prometheus exporter for Windows node, using the WMI (Windows Management Instrumentation). https://github.com/martinlindhe/wmi_exporter

WMI exporter provides the host metrics (CPU, memory, Disk, Network etc). Each Windows node needs to run single instance of WMI exporter.

We can fetch Windows containers metrics also through WMI exporter by calling hcsshim https://github.com/Microsoft/hcsshim

**Comment by brancz** [comment]
I think generally having a separate set of dashboards for windows nodes and workloads is a reasonable thing to have, as long as they can be disabled as in people who simply don't have any windows nodes won't be bothered by it.

**Comment by SubodhBhargava** [comment]
+ @sachinmsft

**Comment by sachinmsft** [comment]
I am working on it. @brancz can you please assign this issue to me.

**Comment by brancz** [comment]
I can only assign members of the organization. But feel free to tackle this :)

**Comment by sachinmsft** [comment]
Sure Frederic.

**Comment by sachinmsft** [comment]
@brancz AFAIK dashboards can not be disabled, they can be moved to disabled folder if are not being used. My plan is to create separate dashboards for all windows resources. So if a person does not have windows nodes then he should not load windows dashboards.  
Please let me know if you have better approach to handle this case.

**Comment by brancz** [comment]
I think having the dashboards in separate files and not include them in the "normal" list of dashboards could be a solution for a start, as that way those who don't have windows compute can just not include them, but those who do just do

```
... // normal jsonnet
+ (import 'kubernetes-mixin/dashboards/windows.libsonnet')
```

**Comment by sachinmsft** [comment]
Thanks. I have sent the PR https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/164 for windows dashboards.

**Comment by metalmatze** [comment]
With #164 merged, I'll close this one now.
