### ISSUE TITLE
exported_namespace label instead of namespace in "Kubernetes / Persistent Volumes" grafana dashboard

### ISSUE THREAD

**Issue by GAHila** [kubernetes-monitoring/kubernetes-mixin#169]
I upgraded all prometheus operator to 0.29 including grafana and its dashboards from: https://github.com/coreos/prometheus-operator/blob/release-0.29/contrib/kube-prometheus/manifests/grafana-dashboardDefinitions.yaml for grafana dashboards. 

"Kubernetes / Persistent Volumes" grafana dashboard has two queries that are looking for exported_namespace label:

```
"query": "label_values(kubelet_volume_stats_capacity_bytes{job=\"kubelet\"}, exported_namespace)",
```
```
"query": "label_values(kubelet_volume_stats_capacity_bytes{job=\"kubelet\", exported_namespace=\"$namespace\"}, persistentvolumeclaim)",
```

However there is no such label in prometheus. I think that this is a accidental bug that needs to be fixed.

Opened an issue in prometheus operator but apparently needs to be actually submitted here.

https://github.com/coreos/prometheus-operator/issues/2463

**Comment by metalmatze** [comment]
Would you like to do the change and create a PR?

It should be simple because you only need to change this and the following query expression. :wink: 
https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/dashboards/persistentvolumesusage.libsonnet#L97

**Comment by nlamirault** [comment]
@metalmatze i think you could close this issue. `exported_namespace` does not seems to be used.
