### ISSUE TITLE
Drill Down Links not working

### ISSUE THREAD

**Issue by thegryfon** [kubernetes-monitoring/kubernetes-mixin#172]
Hi i've successfully generate the yaml file and install on a grafana cluster, but the drill down links (such as from namespace pod to the pod dashboard) is not working (i.e 404 not found). I tried to see the config.jsonnet and there are these ids

```
  grafanaDashboardIDs: {
      'k8s-resources-cluster.json': 'ZnbvYbcXkob7GLqcDPLTj1ZL4MRX87tOh8xdr831',
      'k8s-resources-namespace.json': 'XaY4UCP3J51an4ikqtkUGBSjLpDW4pg39xe2FuxP',
      'k8s-resources-pod.json': 'wU56sdGSNYZTL3eO0db3pONtVmTvsyV7w8aadbYF',
      'k8s-cluster-rsrc-use.json': 'uXQldxzqUNgIOUX6FyZNvqgP2vgYb78daNu4GiDc',
      'k8s-node-rsrc-use.json': 'E577CMUOwmPsxVVqM9lj40czM1ZPjclw7hGa7OT7',
      'nodes.json': 'kcb9C2QDe4IYcjiTOmYyfhsImuzxRcvwWC3YLJPS',
      'pods.json': 'AMK9hS0rSbSz7cKjPHcOtk6CGHFjhSHwhbQ3sedK',
      'statefulset.json': 'dPiBt0FRG5BNYo0XJ4L0Meoc7DWs9eL40c1CRc1g',
    },
```

however the generated id is not any of the above, instead some other number. I tried to see the source code, and it seems there are method to generate dashboard id from filename hash if i'm not mistaken. Is there any specific configuration in order for the drill down to pod to work as it should ?

Thanks.

**Comment by metalmatze** [comment]
I'm not exactly sure what happend. Can you look at the generated YAML and see what the URLs in there look like? Maybe you can also provide more information or a setup, so that we can reproduce the issue.

**Comment by metalmatze** [comment]
Any updates on this?

**Comment by dimm0** [comment]
I have the same issue now. For some reason the dashboard is called "kubernetes-compute-resources-pod" instead of "k8s-resources-pod", with the same ID

**Comment by dimm0** [comment]
Can I provide any other info to fix this?
