### ISSUE TITLE
Adapt to Kubernetes 1.14 metrics overhaul

### ISSUE THREAD

**Issue by brancz** [kubernetes-monitoring/kubernetes-mixin#182]
Now that Kubernetes 1.14 is released, we should make sure that the kubernetes-mixin continues to work correctly with it. This is not the case due to the major metrics overhaul that landed in 1.14.

Here is the changelog list of metric changes:https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md#removed-and-deprecated-metrics

As it will be a while until everyone can be expected to be on 1.14, I suggest we should offer a jsonnet patch to be appended to one's setup to make it comply to the metric changes from 1.14 (or vice versa in which case "dropping" the old behavior will be easier in the future).

@metalmatze @bcotton @csmarchbanks @tomwilkie @gouthamve @paulfantom

**Comment by csmarchbanks** [comment]
I think offering some backwards compatibility is definitely something we should do. I would vote for a patch to support "old" behavior for the "dropping" reason you mentioned.

Do we want the patch to be something a user has to manually apply? Or should we allow a user to set a kubernetes version as a config and apply the patch for them conditionally?

**Comment by brancz** [comment]
> Do we want the patch to be something a user has to manually apply? Or should we allow a user to set a kubernetes version as a config and apply the patch for them conditionally?

I haven't thought about this. I assumed a manual patch, but the version as config seems interesting as well. Who wants to write a semver parser in jsonnet?

**Comment by metalmatze** [comment]
> Who wants to write a semver parser in jsonnet?

:joy: 

Actually, I was thinking about the same, however I think that a simple if else should be enough. Am I missing something?

**Comment by csmarchbanks** [comment]
Depends how the if else is structured. If we had `if version == '1.14' then new-thing else old-thing` it could break when someone moves to 1.15. How many versions would you say we should support?

**Comment by metalmatze** [comment]
My suggestion is to simply have `if higherKubernetes114 then new-thing else old-thing` to have people set a boolean to explicitly opt-out of the 1.14+ changes.

**Comment by brancz** [comment]
How different is that from a patch?
