### ISSUE TITLE
Alert on underprovisioned pods

### ISSUE THREAD

**Issue by metalmatze** [kubernetes-monitoring/kubernetes-mixin#183]
Reading through @tomwilkie blog post on subqueries (https://grafana.com/blog/2019/04/01/how-were-using-prometheus-subqueries-at-grafana-labs./) I thought it might be worth adding the query to find underprovisioned pods?!

```promql
  quantile_over_time(0.95,
    sum by (container_name, pod_name, namespace) (
      rate(container_cpu_usage_seconds_total{namespace="cortex-ops", container_name!="POD"}[5m])
    )[7d:]
  )
>
  sum by (container_name, pod_name, namespace) (
    label_join(
      label_join(
        kube_pod_container_resource_requests_cpu_cores,
        "pod_name", "", "pod"
      ),
      "container_name", "", "container"
    )
  )
```

WDYT @brancz @gouthamve @csmarchbanks ?

**Comment by brancz** [comment]
In a general sense, I like these a lot and maybe would even integrate them into the existing dashboards, but I'm a little worried about their complexity. Maybe a recording rule?

**Comment by csmarchbanks** [comment]
I also like these queries as a good way to suggest requests. I think:
```
quantile_over_time(0.95,
  sum by (container_name, pod_name, namespace) (
    rate(container_cpu_usage_seconds_total{container_name!="POD"}[5m])
  )[7d:]
)
```
should definitely be a recording rule since it is useful for both underprovisioning and finding what the request should be. I am less convinced that the second part needs to be a recording rule, but not against it either.

**Comment by metalmatze** [comment]
Agreed. We can totally go for a recording rule. That's exactly what Grafana did in the past.
