### ISSUE TITLE
KubeAPIErrorsHigh metrics misunderstanding or error?

### ISSUE THREAD

**Issue by richerve** [kubernetes-monitoring/kubernetes-mixin#185]
Currently the definition of the KubeAPIErrorsHigh alert is on the lines of:

```        
sum(rate(apiserver_request_count{job="apiserver",code=~"^(?:5..)$"}[5m]))
  /
sum(rate(apiserver_request_count{job="apiserver"}[5m])) * 100 > 3
```

Isn't it the case that we are comparing a percentage rate to a value 3 in this case, so is saying, alert if there are more than 3% of errors?

I assume that the number to compare would be 30 as in 30%, no?

**Comment by csmarchbanks** [comment]
Your understanding is correct, this alert will trigger if more than 3% of all apiserver requests are failing. Why would you expect the alert not to fire until 30% errors? That is a huge number of errors. We could consider making the values configurable, but I would still expect single digit values.

**Comment by richerve** [comment]
Thank you @csmarchbanks, don't have the context if more than single digit percentages are too high so will just follow the advice.
