### ISSUE TITLE
Host build (or other) docker images in shared spot

### ISSUE THREAD

**Issue by csmarchbanks** [kubernetes-monitoring/kubernetes-mixin#188]
Right now we use private docker repos to host the build docker image. It would be nice if at some point we create a central place for any docker images.

Perhaps a general image with jsonnet + jb installed? Then layer promtool on top of that?

**Comment by metalmatze** [comment]
The idea sounds good to me. The only question I have: Should we create a organization on quay or docker hub?

**Comment by csmarchbanks** [comment]
I have slight preference for quay, but am fine with either.

**Comment by paulfantom** [comment]
> Perhaps a general image with jsonnet + jb installed?

There is one such image already at `quay.io/coreos/jsonnet-ci` and it is used for example in coreos/prometheus-operator and coreos/kube-prometheus.

**Comment by metalmatze** [comment]
Yes. Reusing that image would be probably really good! 👍
