### ISSUE TITLE
Absolute drill down links break when using Grafana under a path

### ISSUE THREAD

**Issue by belcherbrandon** [kubernetes-monitoring/kubernetes-mixin#192]
**Background**
Issue I raised against kube-prometheus: https://github.com/coreos/kube-prometheus/issues/76

Setting Grafana's root_url to %(protocol)s://%(domain)s/grafana/ and running it behind a reverse proxy works for all Grafana application links.  The Grafana pages contain the tag `<base href="/grafana/">` so internal links are relative to the configured path.

**Issue**
In the dashboards provided by the mixin, drill down links are being generated with a leading slash. This makes them absolute (relative to the domain) rather than the base tag that Grafana uses.  This results in a 404.

**Comment by sudeep-ib** [comment]
+1 to this issue as well. Encountering this when running grafana behind nginx with a subdomain /grafana/

Has anyone found a solution for fixing the broken drilldowns provided by kubernetes-mixins ?

**Comment by brancz** [comment]
This probably makes sense to be solved globally, so that all dashboards and links are automatically prefixed. Prime example for jsonnet :)

**Comment by csmarchbanks** [comment]
I think setting the `grafanaK8s.linkPrefix` config variable should fix this, have you tried that?

**Comment by belcherbrandon** [comment]
Yes, this works:
```
_config+:: {
  grafanaK8s+:: {
    linkPrefix: '.',
  },
},
```

This seems like a common enough requirement to warrant a blurb in the readme (the mixin, kube-prometheus, or both).

**Comment by brancz** [comment]
Agreed. Having just gone through this, I'd be great if you could shoot us a PR where you would have expected this :)

**Comment by iangkent** [comment]
Also raised with prometheus-operator helm chart.
https://github.com/helm/charts/issues/14300

**Comment by sudeep-ib** [comment]
I assume this can only work for jsonnet. Is there a way to set this when using helm chart for grafana ?

**Comment by nvtkaszpir** [comment]
> I assume this can only work for jsonnet. Is there a way to set this when using helm chart for grafana ?

unfortunately not directly, but could be used with init container which fetches dashboards and uses sed to replace datasource - something similiar could be used for replacing the '/d/...' into './d/...'

**Comment by andycondon** [comment]
I have a pull request open for this here: #247.

**Comment by kpucynski** [comment]
@andycondon please add reviewers to your PR according to OWNERS file - hope it will speedup things.

**Comment by andycondon** [comment]
@kpucynski Will do next time, thank you.
