### ISSUE TITLE
multiple matches for labels

### ISSUE THREAD

**Issue by wuvs** [kubernetes-monitoring/kubernetes-mixin#193]
Hi, 
I installed prometheus/grafana with helm from charts/stable and copied rules/alerts/dashboards into values.yaml files. everything works fine except for the following rule I get an error:

```
- "expr": |
      count by (node) (sum by (node, cpu) (
        node_cpu_seconds_total{job="prometheus-node-exporter"}
      * on (namespace, pod) group_left(node)
        node_namespace_pod:kube_pod_info:
      ))
  "record": "node:node_num_cpu:sum"
```

```
Error executing query: multiple matches for labels: grouping labels must ensure unique matches
```

K8S version: 1.13.5

Grafana: 
- chart version: 3.3.1
- app version: 6.1.4

Prometheus
- chart version: 8.10.0
- app version: 2.9.0

(node-exporter, kube-state-metrics are enabled within prometheus helm chart)

**Comment by aranair** [comment]
@wuvs I'm seeing the same issue here, how did you resolve this?

**Comment by briend** [comment]
We narrowed our issue down to one exporter pod named `prometheus-operator-prometheus-node-exporter-krtj7`.  We just deleted the pod so it restarted with a new name and. . . it fixed it.  We have no idea why. . .

**Comment by todd-berger** [comment]
> We narrowed our issue down to one exporter pod named `prometheus-operator-prometheus-node-exporter-krtj7`. We just deleted the pod so it restarted with a new name and. . . it fixed it. We have no idea why. . .
@briend 
How did you narrow it down effectively?

**Comment by lyveng** [comment]
@todd-berger We figured out the faulty node by writing a python script to run the prometheus query in a loop with each iteration evaluating data for a specific node. The faulty node returned 422 while the others returned 200. I've added more details and the python code in this [blog post](https://medium.com/@livingstone.s.e/handling-prometheusrulefailures-alert-caused-by-grouping-labels-must-ensure-unique-matches-error-3019d7a7f3d1)
