### ISSUE TITLE
RunbookURL is always lowering the alert name

### ISSUE THREAD

**Issue by mitchellmaler** [kubernetes-monitoring/kubernetes-mixin#197]
Our runbook links/headers are case sensitive but if we try to add the url using the mixin it will always lowercase the alert name. Is there a way to not lower the url and keep the exact alert name case?

**Comment by metalmatze** [comment]
Could you provide an example? I'm not 100% sure I understand your problem, as I don't recall how alert names are lower cased.

**Comment by mitchellmaler** [comment]
It takes the runbookURLPattern that is in the config and calls this local function addRunbookURL which then calls a lower() method to lower the alert name when it adds it to the rule. 
https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/alerts/add-runbook-links.libsonnet#L19
