### ISSUE TITLE
Exclude Alert Groups

### ISSUE THREAD

**Issue by mitchellmaler** [kubernetes-monitoring/kubernetes-mixin#200]
I am trying to figure out how I can exclude certain alert groups using the config.jssonnet file.

**Comment by metalmatze** [comment]
This issue should help you: https://github.com/coreos/prometheus-operator/issues/2250

**Comment by mitchellmaler** [comment]
@metalmatze Those examples in that only show how to filter our a rule or modify a rule. I am trying to filter out a group.

**Comment by nabadger** [comment]
I'm doing something similar now - you could use something like
```
local ignore_groups = ['kube-scheduler.rules']
```
```
{
  // Define a filter function to remove unwanted groups
  filterGroups(ignore_groups):: {
    prometheusAlerts+:: {
      groups: std.filter(
        function(group)
          std.count(ignore_groups, group.name) == 0,
        super.groups
      ),
    },
  },
}
```
