### ISSUE TITLE
Kubernetes / Pods CPU + Network IO flapping while Kubernetes / Compute Resources / Pod does not

### ISSUE THREAD

**Issue by jeanluclariviere** [kubernetes-monitoring/kubernetes-mixin#213]
Hi Folks,
Fairly straight forward, every pod inside of the "Kubernetes / Pod" Dashboard is displaying flapping CPU / network IO, where as each of the pods in the "Kubernetes / Compute Resources / Pod" dashboard do not. Wondering if anyone has seen this and if it's an issue with the way these details are being collected.

![image](https://user-images.githubusercontent.com/11167646/58977549-fc0c8080-8797-11e9-844c-fc85a85f46f9.png)

**Comment by csmarchbanks** [comment]
What is your scrape interval? Could this be related to: https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/212

**Comment by jeanluclariviere** [comment]
Looks like that is most likely the cause, i found that increasing the rate to 2m fixed the issue, so changing my interval from 30s to 15s should hopefully do the trick.
