### ISSUE TITLE
Alert when hpa is running at maxReplicas

### ISSUE THREAD

**Issue by naseemkullah** [kubernetes-monitoring/kubernetes-mixin#222]
I believe this would be a good alert to have so we can know to increase maxReplicas or Requests of the given workload ...unless something similar already exists?

**Comment by brancz** [comment]
I think this is reasonable as an info or at most warning type alert. This doesn't have to mean anything, but in conjunction with other alerts this is valuable information.

**Comment by si-robinson** [comment]
any movement here? We have a CloudWatch logs subscription looking for 
"HorizontalPodAutoscaler" "SuccessfulRescale"
which fires a lambda which in turn notifies slack

But the number of logs returned showing 
"the desired replica count is less than the minimum replica count"
when you hit the limit makes this unwieldy for this setup

Would be good to have an event the first time it happens - or is there something else we could hook in to?
