### ISSUE TITLE
kubeletdown alert not work

### ISSUE THREAD

**Issue by zgfh** [kubernetes-monitoring/kubernetes-mixin#225]
kubeletdown alert not work
you can see, kubelet have no metrics, but `absent(up{job="kubelet"} ` no result, and no alert(good thing: TargetDown have alert)

https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/alerts/absent_alerts.libsonnet#L10

![image](https://user-images.githubusercontent.com/11729624/60259941-f6273c80-990a-11e9-8d85-56ab748ea68b.png)

![image](https://user-images.githubusercontent.com/11729624/60259959-fe7f7780-990a-11e9-8d43-607733bad1cb.png)

**Comment by zgfh** [comment]
same issue: https://github.com/prometheus/prometheus/issues/2882

**Comment by brancz** [comment]
I'm not sure I'm understanding, the queries you show seem to be working as expected.

**Comment by zgfh** [comment]
@brancz thanks for help, my bad, close this
