### ISSUE TITLE
Readme instructions broken

### ISSUE THREAD

**Issue by gouthamve** [kubernetes-monitoring/kubernetes-mixin#23]
```
➜  prometheus git:(master) ✗ ks registry add kausal https://github.com/kausalco/public
➜  prometheus git:(master) ✗ ks pkg install kausal/prometheus-ksonnet
ERROR GET https://api.github.com/repos/kausalco/public/contents//prometheus-ksonnet/parts.yaml?ref=6c037aa65f54edadbdcebd6fc0a2ecf167f19109: 404 Not Found []
```

```
➜  prometheus git:(master) ✗ ks version
ksonnet version: 0.8.0
jsonnet version: v0.9.5
client-go version: v1.6.8-beta.0+$Format:%h$
```

**Comment by gouthamve** [comment]
Could acheive the same thing with: `jb install github.com/kausalco/public/prometheus-ksonnet`

Not sure why we need two registries here.

**Comment by gouthamve** [comment]
```
local prometheus = import "prometheus-ksonnet/prometheus-ksonnet.libsonnet";
local kubernetes = import "kubernetes-mixin/mixin.libsonnet";

prometheus + kubernetes {
  _config+:: {
    namespace: "default",
  },
}
```

If we do this we get each of the alert and recording groups specified twice leading to bad prometheus config.

This is because prometheus-ksonnet already imports the kubernetes-mixing here: https://github.com/kausalco/public/blob/master/prometheus-ksonnet/prometheus-ksonnet.libsonnet#L10

If we do just:
```
prometheus {
```

we should be fine.

**Comment by tomwilkie** [comment]
@gouthamve sorry about this - the prometheus-ksonnet app has been updated to use this directly.  The readme there is up to date. Mind making a PR into this repo to update the README?
