### ISSUE TITLE
Recording rule generating "duplicate sample for timestamp" errors

### ISSUE THREAD

**Issue by simonpasquier** [kubernetes-monitoring/kubernetes-mixin#230]
There are (at least) 2 recording rules producing the same metric name (`namespace:container_cpu_usage_seconds_total:sum_rate`):

https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/3596bcd93d15aad44a8403314c37c2ede04e3d8d/rules/rules.libsonnet#L7-L12

https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/3596bcd93d15aad44a8403314c37c2ede04e3d8d/rules/rules.libsonnet#L30-L39

This generates transient errors in the Prometheus logs when some pods don't have the `name` label. And even if all pods had a `name` label, it would still generate inconsistent data as the label set would be heterogeneous (eg the latter rule generates samples with the `label_name`label while the former doesn't).

```
level=debug ts=2019-07-30T08:12:25.748Z caller=manager.go:542 component="rule manager" group=k8s.rules msg="Rule evaluation result discarded" err="duplicate sample for timestamp" sample="{__name__=\"namespace:container_memory_usage_bytes:sum\", namespace=\"openshift-monitoring\"} => 2516475904 @[1564474345729]"
level=debug ts=2019-07-30T08:12:25.748Z caller=manager.go:542 component="rule manager" group=k8s.rules msg="Rule evaluation result discarded" err="duplicate sample for timestamp" sample="{__name__=\"namespace:container_memory_usage_bytes:sum\", namespace=\"openshift-marketplace\"} => 211025920 @[1564474345729]"
level=debug ts=2019-07-30T08:12:25.748Z caller=manager.go:542 component="rule manager" group=k8s.rules msg="Rule evaluation result discarded" err="duplicate sample for timestamp" sample="{__name__=\"namespace:container_memory_usage_bytes:sum\", namespace=\"openshift-image-registry\"} => 27029504 @[1564474345729]"
level=debug ts=2019-07-30T08:12:25.748Z caller=manager.go:542 component="rule manager" group=k8s.rules msg="Rule evaluation result discarded" err="duplicate sample for timestamp" sample="{__name__=\"namespace:container_memory_usage_bytes:sum\", namespace=\"openshift-cluster-node-tuning-operator\"} => 246497280 @[1564474345729]"
level=debug ts=2019-07-30T08:12:25.748Z caller=manager.go:542 component="rule manager" group=k8s.rules msg="Rule evaluation result discarded" err="duplicate sample for timestamp" sample="{__name__=\"namespace:container_memory_usage_bytes:sum\", namespace=\"openshift-machine-config-operator\"} => 204845056 @[1564474345729]"
level=warn ts=2019-07-30T08:12:25.748Z caller=manager.go:554 component="rule manager" group=k8s.rules msg="Error on ingesting results from rule evaluation with different value but same timestamp" numDropped=5
```

Issue already reported here: https://github.com/coreos/kube-prometheus/issues/134

**Comment by csmarchbanks** [comment]
I don't think either of those rules are used in any dashboards or alerts either. Perhaps we could just delete both rules?

 @brancz @metalmatze  do either of you know why these rules are present?

**Comment by simonpasquier** [comment]
If these rules need to be retained, the latter should probably be renamed (`namespace_label_name:container_cpu_usage_seconds_total:sum_rate`?) and the last part of the query changed to `... kube_pod_labels{%(kubeStateMetricsSelector)s,label_name!=""} `

**Comment by chiefy** [comment]
@csmarchbanks please don't delete them, they are really useful even if they're not used by default grafana / AM rules.

**Comment by brancz** [comment]
@metalmatze I seem to remember we started cleaning these up already no?

**Comment by metalmatze** [comment]
Yep. I also think I've started cleaning this up. But not able to find it right now.

**Comment by brancz** [comment]
Either way, I'm ok with removing the duplicate and aligning the recording rule to naming best practices. @simonpasquier do you think you could take care of that?

**Comment by simonpasquier** [comment]
Sure unless @metalmatze is faster :-)

**Comment by metalmatze** [comment]
I looked for branches or any signs of me removing these. Maybe it was a bad rebase or something. @simonpasquier if you want, go ahead and remove them.
