### ISSUE TITLE
Memory calculation needs a fix

### ISSUE THREAD

**Issue by alok87** [kubernetes-monitoring/kubernetes-mixin#234]
**Why** - https://github.com/coreos/prometheus-operator/issues/1310#issue-320923699
https://github.com/coreos/prometheus-operator/issues/1310#issuecomment-387216413

**More Info** - https://github.com/coreos/prometheus-operator/issues/1310

**Comment by sichvoge** [comment]
@alok87 is that something you might be able to pick up by any chance?

**Comment by brancz** [comment]
Just a heads up for anyone who wants to work on this. These dashboards have recently moved to the node-exporter mixin: https://github.com/prometheus/node_exporter/tree/master/docs/node-mixin

Meaning that if someone were to tackle this, then there would be the best place now, as these dashboards are eventually going to disappear from the kubernetes-mixin project.

**Comment by paulfantom** [comment]
node_exporter mixin doesn't have this problem as it already uses memory calculation mentioned in https://github.com/coreos/prometheus-operator/issues/1310#issue-320923699 as seen in https://github.com/prometheus/node_exporter/blob/master/docs/node-mixin/dashboards/node.libsonnet#L77-L85

**Comment by brancz** [comment]
Lovely. Let's remove the dashboards here? :)
