### ISSUE TITLE
KubePersistentVolumeFullInFourDays - Proposal to increase the "for" clause for the alert.

### ISSUE THREAD

**Issue by P6rguVyrst** [kubernetes-monitoring/kubernetes-mixin#262]
![Screenshot 2019-10-07 at 10 29 12](https://user-images.githubusercontent.com/462006/66300705-a84ca800-e8ed-11e9-81e6-47bd2e065159.png)
![Screenshot 2019-10-07 at 09 45 40](https://user-images.githubusercontent.com/462006/66300719-ada9f280-e8ed-11e9-895b-5eb733c9dd8d.png)

This is the kind of behaviour prometheus-operator storage has. The current definition of KubePersistentVolumeFullInFourDays woke me up today, because it's too sensitive and produces false positives.

The issue I have with this is: **if it’s an alert to give me four days heads up for fixing the issue, why is it triggered after the condition has been met only for 5m?**
Increasing the "for" from 5m to 30m or 1h would reduce noise, while still triggering if there is a problem.

**Comment by P6rguVyrst** [comment]
@metalmatze Created a PR for it.

**Comment by brancz** [comment]
Closed by #288
