### ISSUE TITLE
Resources overview : requests, limits and usage

### ISSUE THREAD

**Issue by nlamirault** [kubernetes-monitoring/kubernetes-mixin#263]
hi
do you want to modify the cluster dashboard (and / or namespace) in order to monitor the use of resources over time (use, requests and limits) ?
This can be interesting for adjusting the values of resources

![screencapture-moonworkers-staging-mysk5-grafana-d-9tD-lu2Zk-kubernetes-compute-resources-overview-2019-10-09-22_19_43 (1)](https://user-images.githubusercontent.com/29233/66517424-6f762400-eae3-11e9-9e07-67fe93237368.png)

**Comment by brancz** [comment]
The gauges on the cluster dashboard already show this no? Are you suggesting to turn the gauges into graphs? (I think I'd be generally ok with that as long as it doesn't clutter up the dashboard too much)

**Comment by brancz** [comment]
Ah sorry I meant the "Headlines". They're singlestats, not gauges.

**Comment by nlamirault** [comment]
Yes !
Turn the singlestats into graphs could be useful to affinate limits and requests according usage.

**Comment by brancz** [comment]
Yeah I think that would be ok, we may want to have it in a different row and by default hide it to de-clutter. But yes generally I think that could be useful.
