### ISSUE TITLE
Provide namespace context to the alerts

### ISSUE THREAD

**Issue by marcindulak** [kubernetes-monitoring/kubernetes-mixin#265]
This is a question related to https://github.com/helm/charts/issues/13335

For the purpose of limiting the scope of alerts I need to add the namespace context to the `TargetDown` and possibly other default alerts. 

I'm installing prometheus using helm, so I could fetch the chart, and locally modify it in https://github.com/helm/charts/blob/2b8054808ca81509d0955a823fce725d699a97ae/stable/prometheus-operator/templates/prometheus/rules/general.rules.yaml#L24-L30, and other places, like this

```
--- templates/general.rules.yaml.orig	2019-10-15 15:17:33.310900715 +0200
+++ templates/general.rules.yaml	2019-10-15 15:34:34.493758968 +0200
@@ -3,12 +3,12 @@
 - name: general.rules
   rules:
   - alert: TargetDown
-    expr: 100 * (count(up == 0) BY (job) / count(up) BY (job)) > 10
+    expr: 100 * (count(up == 0) BY (job, namespace) / count(up) BY (job, namespace)) > 10
     for: 10m
     labels:
       severity: warning
     annotations:
-      description: '{{`{{ $value }}`}}% of {{`{{ $labels.job }}`}} targets are down.'
+      description: '{{`{{ $value }}`}}% of {{`{{ $labels.job }}`}} targets in the {{`{{ $labels.namespace }}`}} namespace are down.'
       summary: Targets are down
   - alert: DeadMansSwitch
     expr: vector(1)
```

I imagine that the alerts provide a limited scope of labels (they exclude the namespace) for a reason. Is there a better way to include additional labels in the context of the alerts than maintaining own copy of the chart?

**Comment by brancz** [comment]
While I do like something like this, I don't think we can actually rely on the namespace label to be present on any setup. If anyone can come up with a generally applicable way to do something like this, I'd be happy to consider it.

**Comment by marcindulak** [comment]
Out of curiosity - what is an example of an use case of `up` without a namespace?

**Comment by brancz** [comment]
A kubelet nominally doesn’t belong to any namespace for example. But fundamentally there is no guarantee at all that people relabel the namespace label onto their targets, the Prometheus operator happens to do that by default but if not using the Prometheus operator then it’s not necessary and I know of a number of setups that don’t do this.
