### ISSUE TITLE
NetworkTransmitErrors alert potentially too sensitive

### ISSUE THREAD

**Issue by sdanbury** [kubernetes-monitoring/kubernetes-mixin#268]
Using prometheus-operator helm installation and the following query is triggering an alarm for every node in my cluster:

![image](https://user-images.githubusercontent.com/935985/66901855-69a6a400-eff7-11e9-96b7-1dc04847f095.png)

It seems to suggest that there is always going to be a non-0 value returned by this query. So either there is a problem at the networking layer on all of my nodes, or alerting on `> 0` might be too restrictive and not allow for a natural/minor level of network transmit errors.

I noticed that there is a node_exporter mixin as well which seems to have the following alert:

https://github.com/prometheus/node_exporter/blob/855a1f1d18b82f24c1e517da44ef36f2ffa35b19/docs/node-mixin/alerts/alerts.libsonnet#L176

Would be good to hear your view on whether we should bump `> 0` to `> 0.1` or `> 0.5` in the query?

**Comment by paulfantom** [comment]
This repository doesn't provide NetworkTransmitErrors alert.

**Comment by sdanbury** [comment]
Oh, that's awkward, posted in wrong repository 😂, apologies!
