### ISSUE TITLE
network-usage and resources dashboards have hardcoded datasource "prometheus"

### ISSUE THREAD

**Issue by den-is** [kubernetes-monitoring/kubernetes-mixin#290]
Some dashboards, especially all network-usage related dashboards have hardcoded datasource "prometheus" instead of some "$variable" value.

It causes problems with `prometheus-operator` helm chart which by default has "Prometheus" datasource.

Issue occurred in downstream helm chart repo here https://github.com/helm/charts/pull/18564
Reported in kube-prometheus repo too https://github.com/coreos/kube-prometheus/issues/288
And is stated in kube-prometheus issue is similar to https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/284

Unfortunately I don't have enough experience time and motivation to mess with jsonnet. But I sincerely believe in more mature contributors and authors of that project.

Affected dashboards are:
Everything in `dashboards/network-usage/*`
and `dashboards/resources.libsonnet`

List of all currently affected files and changes can be found in this commit with manual fix: https://github.com/helm/charts/pull/18375/commits/4e2e7e54fd2d3f41b6f253605600d83d13712fc9

**Comment by brancz** [comment]
I tried these dashboards yesterday and there are some other problematic things as well, like usage of non standard plugins. We’ll need to revise these a bit, sorry for the inconvenience.
