### ISSUE TITLE
KubeJobFailed not useful as it is defined

### ISSUE THREAD

**Issue by richerve** [kubernetes-monitoring/kubernetes-mixin#295]
The current KubeJobFailed alerts looks something like this:

`kube_job_status_failed{job="kube-state-metrics"} > 0`

As  this metrics is a counter I think it doesn't makes sense to alert on raw values as pods that failed at least once will keep triggering the alert. Triggering the alert on rate of change is more useful I think, something like:

`increase(kube_job_status_failed{job="kube-state-metrics"}[5m]) > 0`

Happy to open a PR with this change if it's of interest

**Comment by brancz** [comment]
That makes sense. As a side note if that’s how this value truly behaves, then we should make sure it has the _total suffix. Could you open an issue on kube-state-metrics regarding this?

**Comment by richerve** [comment]
Hi @brancz. I noticed that in `kube-state-metrics` the `kube_job_status_failed` metric is defined as a Gauge. There's also `kube_job_failed`. As I understand the former records a change of status and the latter records only when it fails, although it's not that clear to me in what conditions one is use or the other.

Will review our production metrics and conditions to make sure that the correct metric is used in the alert and also if it behaves like a counter then open an issue and PR in kube-state-metrics.

**Comment by richerve** [comment]
So first thing, `kube_job_status_failed` is not used anymore for the KubeJobFailed alert in the master branch, is instead using `kube_job_failed`. I'm stuck with running k8s 1.12 at the moment so are not using latest master but release-0.1

In any case the behavior for status_failed or failed is not that different. The former tracks the status change and the latter a boolean of "failed|not_failed" conditions. Either if values are 0,1 or 0..n, I'm not sure if values can go down after that.

For example, can a job that has been failing and just recovers after a couple of fails, clean out its failed status counts? In case of `kube_job_failed` is the boolean value going to change if it recovers?

**Comment by richerve** [comment]
This is probably not relevant anymore
