### ISSUE TITLE
Broken rules node_namespace_pod_container:* after installing latest prometheus

### ISSUE THREAD

**Issue by alok87** [kubernetes-monitoring/kubernetes-mixin#298]
We install and manage prometheus in kubernetes using [prometheus operator](https://github.com/coreos/prometheus-operator)
We use jsonnet to keep all configurations part of code.

To install the prometheus we did a `jb update` which created the following [jsonnet file json](https://gist.github.com/alok87/dd37b4efba615a70f4c61304d16c8f8e)

## Info / Versions
It's using latest kuberentes mixin code - 23416282b86f75bff14bf94732c397764d7ba9db
kube-state-metrics (quay.io/coreos/kube-state-metrics:v1.8.0)

## Issue
kube_pod_info is having `pod` and `container_cpu_cfs_seconds` is having `pod_name` This is causing the existing rules to break.

All the `node_namespace_pod_container:* ` rules are broken and there queries are returning **no data**

For example:
For the following the record rule
```
record: node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate
expr: sum
  by(namespace, pod, container) (rate(container_cpu_usage_seconds_total{container!="POD",image!="",job="kubelet"}[5m]))
  * on(namespace, pod) group_left(node) max by(namespace, pod, node) (kube_pod_info)
```

The below sub query - 
```
sum by(namespace, pod, container (rate(container_cpu_usage_seconds_total{container!="POD",image!="",job="kubelet"}[5m]))
``` 

output
<img width="1266" alt="Screenshot 2019-11-20 at 2 09 57 PM" src="https://user-images.githubusercontent.com/9006763/69222460-8b1f2080-0b9f-11ea-9f34-fa7a24bea9f9.png">

It is returning the output without pod in it because the `container_cpu_usage_seconds` does not have pod and but `pod_name` as the label.

Using label replace and replacing the labels for pod name fixes it. But don't want to do this hack. 
```
label_replace((sum by(namespace, pod_name, container) (rate(container_cpu_usage_seconds_total{container!="POD",image!="",job="kubelet"}[5m])) * on(namespace, pod_name) group_left(node) max by(namespace, pod_name, node) (label_replace(kube_pod_info, "pod_name", "$1", "pod", "(.*)"))), "pod", "$1", "pod_name", "(.*)") 
```

Please suggest what should the right change here. I can contribute to give the fix (if it is an issue)

cc @justjkk

**Comment by brancz** [comment]
`master` of kubernetes-mixin supports only Kubernetes v1.14+, where the `pod` and `container` labels are available in addition to the `pod_name` and `container_name` labels. Starting with v1.16 the latter labels are even removed. If you need pre v1.14 support look at the `release-0.1` branch.

**Comment by alok87** [comment]
ok thanks @brancz
