### ISSUE TITLE
Networking / Namespace (Pods) Dashboard has 2 broken singlestat graphs

### ISSUE THREAD

**Issue by angeloskaltsikis** [kubernetes-monitoring/kubernetes-mixin#301]
Hey ,
Thanks for the amazing dashboards.

I have noticed that the following 2 graphs in the 
`Networking / Namespace (Pods)` dashboard
face the problem 
`Cannot read property 'color' of undefined`
using `Grafana v6.0.1 (0c44a04)`

Graphs:
`Current Rate of Bytes Received`
`Current Rate of Bytes Transmitted`

By inspecting the code of the dashboards https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/dashboards/network-usage/namespace-by-pod.libsonnet#L83 i believe that most likely is not the correct way to pass the colors according to https://github.com/grafana/grafonnet-lib/blob/master/grafonnet/singlestat.libsonnet

I am willing to implement a fix and send a PR, however i wanted to verify that this issue happens to others as well.

Thanks in advance

**Comment by brancz** [comment]
I believe you are right, let's get this fixed :slightly_smiling_face: . Would you like to take care of it?

**Comment by metalmatze** [comment]
any updates on fixing this?
