### ISSUE TITLE
CoreDNS dashboard

### ISSUE THREAD

**Issue by nlamirault** [kubernetes-monitoring/kubernetes-mixin#303]
Hi,
the [prometheus-operator chart](https://github.com/helm/charts/tree/master/stable/prometheus-operator) have a CoreDNS [dashboard](https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-coredns.yaml).
What do you think to add this dashboard to the kubernetes-mixin repository ?

**Comment by brancz** [comment]
I don't think they belong here as it's not strictly necessary that you are running CoreDNS as your kubernetes dns provider/plugin. Generally I think this is a good idea to have though, and maybe we could have a separate mixin for coredns, I'd even be happy to have that be part of this org.

**Comment by metalmatze** [comment]
Any updates on creating the dashboard somewhere else? :blush:

**Comment by brancz** [comment]
If anyone is interested I'm also happy to have it be part of this repo that I use to define the coredns manifests themselves: https://github.com/brancz/coredns-jsonnet

Just an idea, I don't care too much. Ideally of course this would be in the coredns project itself.

**Comment by omerlh** [comment]
Added this to my tasks backlog :)
