### ISSUE TITLE
Using a default datasource instead of hardcoded Prometheus

### ISSUE THREAD

**Issue by navi7** [kubernetes-monitoring/kubernetes-mixin#305]
The setup: `Prometheus` deployed via `prometheus-operator` helm chart and `Thanos` enabled. Using provided Grafana dashboards. 

The issue: the datasource name is hardcoded to `Prometheus` like the following block:
```
.addTemplate(
        {
          current: {
            text: 'Prometheus',
            value: 'Prometheus',
          },
          hide: 0,
          label: null,
          name: 'datasource',
          options: [],
          query: 'prometheus',
          refresh: 1,
          regex: '',
          type: 'datasource',
        },
      )
```

To use `Thanos` as a datasource, one needs to manually change it on each dashboard and when Prometheus isn't even added, the dashboards error out. 

Would it be possible/desirable to replace the previous code block with:
```
          current: {
            text: 'default',
            value: 'default',
          },
```

Or, maybe there would be some other approach which would let me switch the datasource by default?

**Comment by brancz** [comment]
Which dashboard is this? We just fixed this for the network dashboards, where we accidentally did this (https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/302). Generally speaking we always want to use the datasource picker/selector.

**Comment by navi7** [comment]
@brancz All of the dashboards. 

I probably didn't make myself clear enough. Currently, the datasource picker/selector is hardcoded to `Prometheus`. Which in my case is not desirable b/c I'd like it to be set to the `default` (because I have created a datasource named `Thanos` and set it to `default`).

**Comment by brancz** [comment]
Ah I see. Yes I think using default makes more sense.

**Comment by navi7** [comment]
@brancz How do we proceed? I can make a PR if that's desirable.

**Comment by brancz** [comment]
Go ahead :)

**Comment by navi7** [comment]
The PR is here: https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/307

I have one issue, described in the PR.

**Comment by baez90** [comment]
I have a similar problem because we have multiple data sources and I would like to parameterize the name of the used data source.
I created a PR #666 that allows to set a custom data source name.

Is this something you're interested?

**Comment by navi7** [comment]
Closed by: https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/307
