### ISSUE TITLE
Feat. request: Alerts for pod resource usage nearing resource limit

### ISSUE THREAD

**Issue by naseemkullah** [kubernetes-monitoring/kubernetes-mixin#311]
IMHO these would be excellent to have, for memory, cpu and ephemeral-storage. Thoughts? cc @brancz

**Comment by brancz** [comment]
I think those kinds of alerts are typically not generally applicable. I think it would be ok having them under the condition that they are not shipped by default but have to be added with specific labelselectors to be scoped.

**Comment by naseemkullah** [comment]
I see, could you please elaborate to why this is not generally applicable?

My thinking was that if a workload is running very close to or even at the limit of a resource for a defined period of time, it should be raised. Why is this not always the case? There are workloads which will steadily consume a fixed amount of resource and no more, and therefore you would want that to be extremely close to the limit?

**Comment by brancz** [comment]
It may very well be that workloads run at or close to their CPU limit most of the time (we have workloads like that), same goes for memory (especially when there is memory eviction involved), and we haven't even started to discuss based on which memory metric this would even happen :)

**Comment by naseemkullah** [comment]
@brancz What if we changed this to be alert if a resource is being consumed above its requested amount for a window of time?

e.g. a sidecar container that requests 10Mi is consuming 25Mi for 15 minutes, is that not something generally applicable as an alert?

**Comment by brancz** [comment]
That timeframe is subjective, it may very well be that one intentionally underprovisions/overcommits for legitimate reasons.

**Comment by metalmatze** [comment]
"I pay for those cores, so I want to utilize them to the fullest" might be exactly what some folks are doing, so I agree with Frederic, that this really is a super subjective topic und depends on the application at hand. 
Generally, it's better to alert on the latency of your application for example, so that you might see that you need more CPU to reduce the latency again.

No comments for 2 months, so I'm closing this. :blush:
