### ISSUE TITLE
How to add extra labels to each expression and templating in dashboards

### ISSUE THREAD

**Issue by g563** [kubernetes-monitoring/kubernetes-mixin#313]
Currently there's a documented way to only add a cluster label by modifying the config. It'd be great to be able to add any number of extra labels required.

Here's a hacky way of doing what I described by jamming extra variables into `clusterLabel` (it works for expressions but breaks cluster label template/variable):
```
local kubernetes = import 'kubernetes-mixin/mixin.libsonnet';
kubernetes {
  _config+:: {
    showMultiCluster: true,
    clusterLabel: 'extraLabelOne="$extraLabelOne", extraLabelTwo="$extraLabelTwo", cluster',
  },
}
```

What's the proper way of doing something like that and is there a way I can also add those `$extraLabelOne` and `$extraLabelTwo` into templating section for every Grafana dashboard?

**Comment by brancz** [comment]
This is generally a problem with Grafana’s approach to completing queries unfortunately. Can you elaborate on your use case a bit, maybe we can find a solution anyways :)

**Comment by g563** [comment]
Thanks for the quick response @brancz 

The use case is the requirement from internal implementation of PromQL datasource for specific labels to be specified (they're also appended when publishing). It's very similar to `cluster` label, just covers internal needs.

Here's my new workaround:
```
// utils.libsonnet
{
  appendExtraLabels:: {
    rows: [
      row {
        panels: [
          panel {
            targets: [
              target {
                expr: std.strReplace(super.expr, "{", '{extraLabelOne="$extraLabelOne",extraLabelTwo="$extraLabelTwo",'),
              }
              for target in super.targets
            ],
          }
          for panel in super.panels
        ],
      },
      for row in super.rows
    ],
  },
appendExtraTemplates:: {
    templating+: {
      list+: [
        {
          allValue: null,
          current: {},
          datasource: $datasource,
          hide: false,
          includeAll: false,
          label: "extraLabelOne",
          multi: false,
          name: "extraLabelOne",
          options: [],
          query: 'custom_query',
          refresh: 1,
          regex: '',
          sort: 2,
          tagValuesQuery: '',
          tags: [],
          tagsQuery: '',
          type: 'query',
          useTags: false,
        },
...
```

Still far from perfect but at least _almost_ gets the job done.

**Comment by brancz** [comment]
Hmm I see what you mean, I’m not sure it fits your bill but for similar purposes (of enforcing a particular label in queries) we built https://github.com/openshift/prom-label-proxy. Would that work for you?

**Comment by g563** [comment]
Thanks for sharing @brancz . It's something I'll keep it in mind but it's not something that will help in my particular case at this moment.

You could compare the use case to Splunk indexes where logs are published into a specific index and when querying (e.g. `index="my-space" <query>`) you have to specify which index you want to look into for faster queries or `*` for slow queries across all indexes. By doing what I posted above you get a nice dropdown of all available indexes to choose from.

If they modified the request and required labels are not present they'll just receive an error (already implemented in PromQL compatible backend).

**Comment by brancz** [comment]
Hmm .. unfortunately I don't have a better idea, I feel the use case is rather niche and what you have done works good enough it seems. If you have an idea that isn't too invasive I'd be happy to discuss but I'm not sure I can think of something off the top of my head.
