### ISSUE TITLE
Dashboard format error : "true" as a string instead of boolean 

### ISSUE THREAD

**Issue by yogeek** [kubernetes-monitoring/kubernetes-mixin#314]
I generated the dashboards with jsonnet and when trying to import them in a Grafana instance, some are erroneous.
I first opened an issue on [grafana-operator](https://github.com/integr8ly/grafana-operator/issues/93) repo because I am using it to create dashboard in Grafana but it appeared that the issue was coming from the dashboards in this repo. Here is the conclusion of the investigation : https://github.com/integr8ly/grafana-operator/issues/93#issuecomment-567367225

And indeed, when I replaced all `"true"` by `true` in the JSON resulting from the jsonnet generation, the dashboards were imported correctly.

Is seems that these `"true"` strings are coming from the libsonnet graphPanel definition (for example here : https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/dashboards/controller-manager.libsonnet#L22) but I do no know jsonnet very well and I do not understand why such libsonnet definition results in the following JSON where all "true" are strings and all "false" are boolean :
```
"legend": {
                  "alignAsTable": "true",
                  "avg": false,
                  "current": "true",
                  "max": false,
                  "min": false,
                  "rightSide": "true",
                  "show": "true",
                  "total": false,
                  "values": "true"
               },
```

**Comment by brancz** [comment]
Thanks a lot for reporting this! That should have never worked, we just need to remove the quotes from the boolean values. Do you want to shoot us a PR? :)

cc @povilasv (just pining you initially created these dashboards iirc right?)

**Comment by yogeek** [comment]
@brancz ok just created #317

**Comment by brancz** [comment]
Merged. Could you confirm that this now works as expected?

**Comment by yogeek** [comment]
@brancz Sorry but I missed some boolean values in other files... is it possible to complete the PR once it has been merged or should I open a new one ?

**Comment by brancz** [comment]
Whops. That will require another one.

**Comment by yogeek** [comment]
ok here it is : #318 (sorry about that...)

**Comment by brancz** [comment]
No worries at all. Could you just quickly confirm it works now as expected after the second merge? :)

**Comment by yogeek** [comment]
@brancz I confirm that all is ok after the second merge. Thank you for your patience :)
