### ISSUE TITLE
Runbook needs to be updated to include alert-name-kubehpamaxedout

### ISSUE THREAD

**Issue by raoofm** [kubernetes-monitoring/kubernetes-mixin#316]
https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/runbook.md

This is referenced from https://github.com/coreos/kube-prometheus/blob/master/manifests/prometheus-rules.yaml#L606

Relate issue https://github.com/coreos/kube-prometheus/issues/339

**Comment by brancz** [comment]
Feel free to create a runbook :)

**Comment by angelovopsan** [comment]
+1
