### ISSUE TITLE
Dashboards : tags are now supposed to be strings (instead of arrays)

### ISSUE THREAD

**Issue by yogeek** [kubernetes-monitoring/kubernetes-mixin#319]
Hello, apparently, tags seems to be configured as "arrays" in the jsonnet templates but apparently they are now supposed to be "strings".

cf. dicussion and debug here : https://github.com/integr8ly/grafana-operator/issues/93#issuecomment-568183228

Can you confirm this is correct please ?
I would be glad to make a PR but I do not know jsonnet and need some help to identify the files to fix...

**Comment by brancz** [comment]
Sounds like just like we do with promtool regarding checking the prometheus rules, we should also do some linting etc on the dashboards.

**Comment by brancz** [comment]
Judging by the [Grafana JSON Model](https://grafana.com/docs/grafana/latest/reference/dashboard/) it actually seems to me like an array of strings is correct.

**Comment by yogeek** [comment]
@brancz The upstream [issue](https://github.com/integr8ly/grafana-operator/issues/93#issuecomment-568183228) has been closed because most of the schema issues came from the usage of a granfa-sdk to import the dashboards instead of importing directly the raw JSON. Now the SDK has been removed and all seems ok !
Thanks for your help
