### ISSUE TITLE
Add dashboards/alerts for TCP retransmits

### ISSUE THREAD

**Issue by omerlh** [kubernetes-monitoring/kubernetes-mixin#320]
TCP retransmits are exposed by node_exporter (node_netstat_Tcp_RetransSegs), and could indicate a network issue. I think it worth adding it to the network dashboard, and maybe even add an alert for it. See the discussion on this issue prometheus/node_exporter#1023 for more details.

**Comment by brancz** [comment]
I think that would be a great addition!
