### ISSUE TITLE
Network dashboards should support multi cluster

### ISSUE THREAD

**Issue by omerlh** [kubernetes-monitoring/kubernetes-mixin#325]
Currently, those dashboards do not support the multi-cluster label selector - making it hard to use them on envs with multiple clusters.

**Comment by brancz** [comment]
They should. Do you want to fix this? :)

**Comment by omerlh** [comment]
Yeah, I started to work on that - but that noticed that the resources dashboards has some of the dashboards from the network, and already support multi-cluster. So maybe it is better to first decide what should be where?

**Comment by brancz** [comment]
I think if there is a reasonable way to combine the dashboards then I’m all for it!

**Comment by omerlh** [comment]
The main difference at this point is the pie chart I think, and there was already an issue about it - as it's not standard (I can't find it right now...). Maybe it's time to merge them and get rid of the pie?

**Comment by brancz** [comment]
Yes I’m in favor of that.

**Comment by omerlh** [comment]
I'm on it, fighting with Grafana rows now :(

**Comment by paulfantom** [comment]
[Piecharts are no more](https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/338) :tada:

**Comment by omerlh** [comment]
Ok, so this appears to be more complex than I thought at first place: network dashboards are built using `graffonet` while the resources dashboards are built using `graffana-builder`. This is important because (to the best of my experience so far) having multiple panels in each row, and having each panel to take the whole row width (instead of multiple panels in the same grid line) is impossible. Look like `graffonet` allows you to add a row with panels to the `panel` property (while flatting out the row `panels` property), while `graffana-builder` does not support it - so you add rows to `row` property. This is the main difference I noticed, and I think this is what cause the issue. Is this refactor (moving everything to `graffonet`) is reasonable?

**Comment by brancz** [comment]
I don't have a strong opinion on either libraries although grafonnet seems to be the more widely used one. I'm happy with having it be refactored to grafonnet.
