### ISSUE TITLE
Improve resources dashboards

### ISSUE THREAD

**Issue by omerlh** [kubernetes-monitoring/kubernetes-mixin#329]
Those dashboards are really good, but I think they can be better with the following improvements:
* Add CPU throttling metric (container_cpu_cfs_throttled_seconds_total). Also adding a line on 100ms to indicate which value should be problematic.
* Resources dashboards (CPU/Memory) - add resource quota as a horizontal line on the graph, making it easier to understand if/when the quota was breached.

What do you think?

**Comment by brancz** [comment]
I’m assuming you’re saying these in the scope of the pod dashboard right? If so then I’d be very to have this!

**Comment by omerlh** [comment]
On the pod dashboard for sure, maybe also on the namespace dashboard?

**Comment by brancz** [comment]
I feel like on the namespace it would be a bit too cluttered, and if at all should probably just show resource quota if available.

**Comment by omerlh** [comment]
Maybe just adding the namespace quota line?

**Comment by brancz** [comment]
I think having the namespace quota line would be ok.

**Comment by omerlh** [comment]
Great, will work on that also.
