### ISSUE TITLE
Handle absence of scheduler and controller-manager in a more convenient way

### ISSUE THREAD

**Issue by beorn7** [kubernetes-monitoring/kubernetes-mixin#330]
On managed K8s platforms, the metrics for scheduler and controller-manager are not necessarily accessible.

In that case, there is no good choice to set `kubeSchedulerSelector` and `kubeControllerManagerSelector`. For both, there are absence alerts (cf. #200 where the use case is to filter out the absence alert for the scheduler) and dashboards. The dashboards are useless, but they could just be ignored, while the absence alerts will always fire.

Currently, I guess, those have to be hidden in the local config, which is quite tedious. Would be nice if there was a more convenient way, e.g. setting the selectors to empty strings.

Or I am missing something here…

**Comment by brancz** [comment]
Filtering out the alert group should be easy enough no?

**Comment by beorn7** [comment]
In principle, yes. However, you have to filter out the alert group _and_ you have to disable the dashboard, _and_ the whole thing feels like low-level tweaking. However, I'd expect this issue to be very common (probably relevant for everybody using a managed K8s offering), and it would be really nice if there were an easy "flip this switch if you don't have a scheduler to scrape".

**Comment by brancz** [comment]
Sorry I should have been more precise. We could write a pretty easy jsonnet patch that removes the alert group and dashboard. Then anyone who uses a managed kube can just apply that patch. What do you think?

**Comment by beorn7** [comment]
Depends on the usability. As long as it boils down to "flip this switch", I think it's just an implementation detail if we use a jsonnet patch or a conditional.

**Comment by brancz** [comment]
Agreed, I tend to prefer patches when possible but you’re right.
