### ISSUE TITLE
Move promgrafonnet to separate repository

### ISSUE THREAD

**Issue by sh0rez** [kubernetes-monitoring/kubernetes-mixin#331]
When installing this library using `jb`, we end up with the following in `jsonnetfile.lock.json`:

```json
{
  "name": "promgrafonnet",
  "source": {
    "git": {
      "remote": "https://github.com/kubernetes-monitoring/kubernetes-mixin",
      "subdir": "lib/promgrafonnet"
    }
  },
  "version": "20603cc76acdb00363aa3e33006c95d2cfaab0e5",
  "sum": "VhgBM39yv0f4bKv8VfGg4FXkg573evGDRalip9ypKbc="
}
```

Apparently, some downstream dependency has a dependency on this repo itself .... so we install `promgrafonnet` twice, which I imagine can become quite unexpected and hard to debug eventually.

What about moving the lib to `kubernetes-monitoring/promgrafonnet` or `grafana/jsonnet-libs/promgrafonnet` instead?

/cc @metalmatze @brancz

**Comment by brancz** [comment]
I'm happy with having it in `grafana/jsonnet-libs/promgrafonnet`.

**Comment by skl** [comment]
This doesn't look applicable any more, closing.
