### ISSUE TITLE
container cpu alert

### ISSUE THREAD

**Issue by omerlh** [kubernetes-monitoring/kubernetes-mixin#333]
Use node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate to raise an alert when the CPU usage is a lot higher from the container request/limit. 
Consider adding an alert on the container CPU throttling.

**Comment by metalmatze** [comment]
We don't really want to alert on high CPU utilization. There are clusters and users who want high utilization and their applications will work just fine.
It's not a good indicator to alert on. Use something like 99th percentile and error rates instead.
