### ISSUE TITLE
USE method / cluster utilization wrong (should divide by number of nodes)

### ISSUE THREAD

**Issue by lentzi90** [kubernetes-monitoring/kubernetes-mixin#334]
I think all the utilization graphs on the USE method / cluster dashboard are a bit broken as they are now. They seem to show the utilization for the cluster on a scale from 0 - 100 %, but in reality they show the individual utilization for each node stacked on top of each other. This means that the range is in fact 0 - N*100 %, where N is the number of nodes. (If the "bottom" node in the graph is at 100 % it will completely fill the graph as it is now.)

Example: Let's say I have 3 nodes with 50 % CPU utilization each. Then the USE method / cluster graph for CPU utilization will show me a value of 150 %. This is outside the Y-axis max, and not very intuitive. I would expect a value of (50 + 50 + 50) / 3 = 50 % since the cluster is used to 50 % of its capacity.

Does this make sense? Could we change the queries to divide by the number of nodes?

**Comment by metalmatze** [comment]
Yes. It makes sense and one could argue both ways. I recall a previous discussion with @beorn7 on a similar issue in node-exporter. Maybe we can learn from that. 

I'm not sure if having a 50% utilized CPU be shown as 12.5% utilized when it scaled to be 100%.

**Comment by beorn7** [comment]
For stacked graphs, we indeed opted elsewhere to normalize so that usage of all resources would result in 100%. There is a case against stacked graphs in general, which also has its merits. But stacking graphs and not normalizing is definitely not helpful.

**Comment by beorn7** [comment]
In different news: The USE method dashboards here in the kubernetes-mixin are for MS Windows only. The Linux dashboards have been removed in lieu of those offered by the node-mixin.

And yes, I guess it makes sense to keep the MS Windows dashboards in line with the node-mixin dashboard, so please check there for recent updates: https://github.com/prometheus/node_exporter/tree/master/docs/node-mixin

(Having said all of that, personally I think we should revisit the stacked dashboards at some point. I'm still undecided if they make sense or not.)

**Comment by lentzi90** [comment]
Oh I didn't realize that this dashboard wasn't part of the kubernetes-mixin! I installed the prometheus-operator with all default dashboards and simply assumed all of them came from this project. But I can see now that only some have the `kubernetes-mixin` label!

I guess I should open an issue in the node_exporter repo instead then?

**Comment by beorn7** [comment]
Are you using the latest version of both, the kubernetes-mixin and the node-mixin? Because all the _USE method / cluster_ seem to have the proper scaling already as I look at them right now.

**Comment by lentzi90** [comment]
I'm on version 8.3.3 of the prometheus-operator chart (latest is 8.5.10). The dashboards included haven't changed though. They are about 2 months old so I guess that is the issue. :slightly_smiling_face:

If I'm not mistaken, the dashboard I'm talking about is coming from [this template](https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/grafana/dashboards-1.14/node-cluster-rsrc-use.yaml). I guess quite a lot may have happened in the 2 months since they last updated that. Will see if I can get someone to update the helm chart!

**Comment by beorn7** [comment]
Wild guess: If you are using K8s before 1.14, then you have to use v0.1.0 of the kubernetes mixin (because the newer versions require the new metrics that happened after the metrics overhaul in 1.14). And v0.1.0 of the kubernetes-mixin still contains the old USE node dashboards with the normalization issues.

**Comment by lentzi90** [comment]
Good point! I'm on k8s v1.15 though and the dashboard template I linked to is specifically for v1.14 and newer, but I can see that they do have even older dashboards for older versions of k8s. (There is one folder `dashboards` for < v1.14 and one `dashboards-1.14` for >= v1.14.)

**Comment by chriscasumo** [comment]
> In different news: The USE method dashboards here in the kubernetes-mixin are for MS Windows only. The Linux dashboards have been removed in lieu of those offered by the node-mixin.
> 
> And yes, I guess it makes sense to keep the MS Windows dashboards in line with the node-mixin dashboard, so please check there for recent updates: https://github.com/prometheus/node_exporter/tree/master/docs/node-mixin
> 
> (Having said all of that, personally I think we should revisit the stacked dashboards at some point. I'm still undecided if they make sense or not.)

Hi there, apologies to hijack an old thread. I appreciate the graphs and all the work that went into them, however I think that a generalised stacked graph approach may be misleading, especially when viewing graphs that show metrics of a specific pod or deployment set. In my opinion, that would make sense on a cluster-wide view, but when drilling down I believe that better clarity is appreciated.
Is this something that you would consider a PR for?

**Comment by brancz** [comment]
Could you draft up the difference and share maybe some screenshots? Maybe we can make a better call that way. I tend to agree that stacked graphs don't make sense (we also have clusters with 100s of nodes at which point it just becomes one blur anyways).
