### ISSUE TITLE
KubeVersionMismatch firing on EKS (apiserver: v1.14.9; kubelet: v1.14.7)

### ISSUE THREAD

**Issue by syst0m** [kubernetes-monitoring/kubernetes-mixin#342]
Using `prometheus-operator` v8.5.11 chart with helm, on EKS controlplane/apiserver v1.14.9.
The `kubelet` version on the nodes is v1.14.7.
The `KubeVersionMismatch` alert is firing continuously.

According to the k8s docs, re. skew policy, this case should be fine,
as the `kubelet` is two minor versions older than the `apiserver`.
See: https://kubernetes.io/docs/setup/release/version-skew-policy/#kubelet

There is no AMI v1.14.9 for the worker nodes, so there's no way to fix this alert.

I see that there have been similar issues and PRs, trying to address this issue, in the past:
[#144 ](https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/144)
[#255 ](https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/255)
[#289 ](https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/289)

**Comment by keeganwitt** [comment]
I've got a bit different set of versions, but am experiencing the same problem. In addition to the attempts syst0m mentioned, there is also #150. I see OpenShift [removed](https://github.com/openshift/cluster-monitoring-operator/pull/611) the rule entirely. Maybe that's what EKS users will have to do as well, though I'd prefer if that weren't the case.

Here's the versions I'm working with

```
> helm ls | grep monitoring
monitoring              	2       	Mon Sep  9 12:43:07 2019	DEPLOYED	prometheus-operator-6.6.1         	0.31.1        	monitoring

> kubectl get nget nodes -o custom-columns=VERSION:.status.nodeInfo.kubeletVersion
VERSION
v1.14.8-eks-b8860f
v1.14.8-eks-b8860f
v1.14.8-eks-b8860f
v1.14.8-eks-b8860f
v1.14.8-eks-b8860f
v1.14.8-eks-b8860f
v1.14.8-eks-b8860f
v1.14.8-eks-b8860f

> kubectl get version | tail -n 1
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

> kubectl  -n monitoring get -o yaml PrometheusRule/monitoring-prometheus-oper-kubernetes-system | grep KubeVersionMismatch -A 9
    - alert: KubeVersionMismatch
      annotations:
        message: There are {{ $value }} different semantic versions of Kubernetes
          components running.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubeversionmismatch
      expr: count(count by (gitVersion) (label_replace(kubernetes_build_info{job!="kube-dns"},"gitVersion","$1","gitVersion","(v[0-9]*.[0-9]*.[0-9]*).*")))
        > 1
      for: 1h
      labels:
        severity: warning
```

Even though I don't have the latest chart, https://github.com/coreos/kube-prometheus/blob/master/manifests/prometheus-rules.yaml#L785 has `count(count by (gitVersion) (label_replace(kubernetes_build_info{job!~"kube-dns|coredns"},"gitVersion","$1","gitVersion","(v[0-9]*.[0-9]*.[0-9]*).*"))) > 1`, which matches the expression my version is running.

**Comment by keeganwitt** [comment]
If we primarily care about the kubelet versions and not the API server versions (which is generally the case for managed K8s instances), you could use an expression like `count(count by(gitVersion) (label_replace(kubernetes_build_info{job!="kube-dns"}, "gitVersion", "$1", "gitVersion", "(v[0-9].[0-9]).*"))) > 2`. If you wanted to try to capture both [skew policies](https://kubernetes.io/docs/setup/release/version-skew-policy/#supported-version-skew) with a single rule, I think  `count(count by(gitVersion) (label_replace(kubernetes_build_info{job!="kube-dns"}, "gitVersion", "$1", "gitVersion", "(v[0-9].[0-9]).*"))) > 1` would be a more appropriate rule than the one currently in place.

**Comment by zjj2wry** [comment]
encounter this problem in EKS cluster, I think minor version skew does not alerting is acceptable. i can create a PR for it
