### ISSUE TITLE
Alert KubeDaemonSetMisScheduled is too sensitive

### ISSUE THREAD

**Issue by omerlh** [kubernetes-monitoring/kubernetes-mixin#347]
See the discussion kubernetes/kube-state-metrics#812

Due to autosclaer, when a new node starts there is a short period when a daemonset has one pod still not scheduled for a short period:

![image](https://user-images.githubusercontent.com/6730584/73963535-21e6b800-4919-11ea-982d-3b482c1a1eea.png)

I think it worth adding `for` to the alert, so it will fire only after a defined time period - 5 minutes at least.

**Comment by brancz** [comment]
Happy with a 5min for clause.

**Comment by djsly** [comment]
here's a few examples when the cluster auto scaler kicks in...

seems that 5min won't be long enough...

<img width="1777" alt="Screen Shot 2020-06-24 at 10 26 48 PM" src="https://user-images.githubusercontent.com/4981802/85646331-e18a9b00-b669-11ea-93c9-2e72d635a50f.png">
<img width="464" alt="Screen Shot 2020-06-24 at 10 26 35 PM" src="https://user-images.githubusercontent.com/4981802/85646334-e2233180-b669-11ea-9531-8e7abed7dd1f.png">
<img width="396" alt="Screen Shot 2020-06-24 at 10 26 31 PM" src="https://user-images.githubusercontent.com/4981802/85646336-e2bbc800-b669-11ea-9407-13c5c22d6899.png">
<img width="446" alt="Screen Shot 2020-06-24 at 10 26 25 PM" src="https://user-images.githubusercontent.com/4981802/85646337-e2bbc800-b669-11ea-8f49-111c2fdd5e28.png">
<img width="402" alt="Screen Shot 2020-06-24 at 10 26 21 PM" src="https://user-images.githubusercontent.com/4981802/85646338-e2bbc800-b669-11ea-8986-76091779602f.png">
<img width="403" alt="Screen Shot 2020-06-24 at 10 26 17 PM" src="https://user-images.githubusercontent.com/4981802/85646339-e2bbc800-b669-11ea-9461-833847dcdc65.png">
<img width="393" alt="Screen Shot 2020-06-24 at 10 26 11 PM" src="https://user-images.githubusercontent.com/4981802/85646340-e3545e80-b669-11ea-8a86-cd8800023438.png">

**Comment by brancz** [comment]
Looks like a for statement with 15m has already been added ~3 months ago. Could you update your rules and check if that works for you? :)

**Comment by djsly** [comment]
awesome! I will check the prom-operator chart to see it it was picked up

**Comment by djsly** [comment]
https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/prometheus/rules/kubernetes-apps.yaml#L129-L136

seems they have put 10m .

**Comment by djsly** [comment]
https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-apps.yaml#L149-L156

15min in >1.14  :)   thanks

**Comment by aantn** [comment]
If anyone else is interested, you can also [do this with Robusta using a node `post_restart_silencer`](https://docs.robusta.dev/master/catalog/actions/alerts.html#adding-a-silencer)
