### ISSUE TITLE
KubePodCrashLooping caclulation

### ISSUE THREAD

**Issue by manlme** [kubernetes-monitoring/kubernetes-mixin#348]
we met that the pods restarted twice within 30s, and then it was OK. but it was alerted.

rate(kube_pod_container_status_restarts_total{%(prefixedNamespaceSelector)s%(kubeStateMetricsSelector)s}[15m]) * 60 * 5 > 0

**Comment by brancz** [comment]
>0 is probably too aggressive. Although anything other than 1 would also seem arbitrary and 1 would still alert for you. I think for this to work we need a multi window approach. Like more than once in the past 15min and any occurrence in the last 5min.
