### ISSUE TITLE
$cluster label not populate - kube-apiserver

### ISSUE THREAD

**Issue by joshbranham** [kubernetes-monitoring/kubernetes-mixin#350]
I noticed on the kube-apiserver dashboard that it has a variable for `$cluster` which comes from `label_values(apiserver_request_total, cluster)` however none of my `apiserver_request_total` metrics have that label. I am running the `kube-prometheus` stack and have the latest `kind: ServiceMonitor` for scraping `kube-apiserver` metrics up. I am having a hard time trying to figure out where that label is supposed to come from and why it is not.

**Comment by olegmayko** [comment]
is it not similar to #343?

**Comment by joshbranham** [comment]
I saw that one but it was not entirely clear what he meant by `cluster is managed by someone else`. I am deploying via `prometheus-operator` and not the helm chart. My scraping targets (Generated via ServiceMonitors) match the `kube-prometheus` project

**Comment by brancz** [comment]
This is meant for if you are monitoring multiple clusters and the cluster label would be added as an external label in prometheus for example.

**Comment by joshbranham** [comment]
Right, so it looks like the default `make dashboards_out` is building with `showMultiCluster=true`. I will look into generating myself with that disabled then as that seems to be the solution.

**Comment by joshbranham** [comment]
So the `apiserver` dashboard is disregarding the `cluster` variable, which makes sense since the default is `false`. However this seems to render the dashboard not working since my `job` label is `apiserver` not `kube-apiserver`. Different issue, will keep digging.

**Comment by brancz** [comment]
> So the apiserver dashboard is disregarding the cluster variable, which makes sense since the default is false.

Correct.

> However this seems to render the dashboard not working since my job label is apiserver not kube-apiserver. Different issue, will keep digging.

For that you just need to configure the job label for your apiserver: https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/7f099821b29bb6f792c5a0833e74db142eba272a/config.libsonnet#L25

**Comment by joshbranham** [comment]
Got it okay, I was confused since all the pre-canned dashboards worked but this one, I will generate it with that field modified. Thanks so much for your help, will close.
