### ISSUE TITLE
Some graphs doesn't render due to scrape interval

### ISSUE THREAD

**Issue by povilasv** [kubernetes-monitoring/kubernetes-mixin#353]
Currently some graphs don't render due to `1m` ranges in some of the queries, e.g:

https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/dashboards/resources.libsonnet#L130

https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/dashboards/resources.libsonnet#L1272

I use default `1m` prometheus scrape interval. 

I was wondering whats the best approach to solve this issue in jsonnet? I wouldn't want to change my scrape interval as it would increase my Prometheus disk size, etc.

**Comment by brancz** [comment]
I think we should add an interval picker to each dashboard that does this and default to __interval__ or whatever it is that makes Grafana choose a good value according to the pixels available.

**Comment by povilasv** [comment]
Just to clarify, you are referring to https://grafana.com/docs/grafana/latest/reference/templating/#the-interval-variable right?

**Comment by brancz** [comment]
Yes.

**Comment by povilasv** [comment]
This is fixed.
