### ISSUE TITLE
Termination event  per workload count

### ISSUE THREAD

**Issue by naseemkullah** [kubernetes-monitoring/kubernetes-mixin#354]
Would it make sense to track these? Either for alerting or graphing purposes?

Potentially with `kube_container_status_terminated_reason` metric?

cc @brancz

**Comment by brancz** [comment]
What exactly would we be answering with that? I think we could probably do this but need to make sure that this is accurately explained in the dashboard.

**Comment by naseemkullah** [comment]
To correlate termination events with a reduction in availability and know the cause e.g. a spike in a certain kind of termination event.

This would make it more easy to correlate things like a cascading failure for a service where all pods start failing their liveness checks.

Basically be able to keep an eye on termination events.

**Comment by brancz** [comment]
> Basically be able to keep an eye on termination events.

I'm a strong believer of non-human alerting :) if we can come up with useful alerts then I'm happy to have an accompanying dashboard.

**Comment by naseemkullah** [comment]
As am I!

There is an alert set up for pods frequently restarting, basically the idea is to add some info about the why.... This would basically add a visualization to the pod frequently restarting alert, adding in the count per reason. Or something like that....

**Comment by brancz** [comment]
I think this would be ok to try, and if it turns out the be flaky we can still remove/adjust it.

**Comment by brancz** [comment]
Note that especially for OOMKills we are currently exploring more precise metrics that could get us more reliable data (RE: https://github.com/kubernetes/kubernetes/pull/87856).

**Comment by naseemkullah** [comment]
I've got this so far, which shows us an increase in termination by reason for a given workload:

![image](https://user-images.githubusercontent.com/24660299/75413186-e37a6280-58f2-11ea-8f08-baf6d5919877.png)

Query used:
```
sum(increase(kube_pod_container_status_last_terminated_reason{pod=~"^$Deployment$Statefulset$Daemonset.*$", reason!="Completed"}[1m])) by (reason) > 0
```

Thoughts? If you like, how and where could this be implemented in mixin?

**Comment by brancz** [comment]
I think this might be more of a case of “interesting queries” to document, but it feels a bit too vague for setting this in stone with a dashboard and or alerting rule.

**Comment by naseemkullah** [comment]
Yes I agree it is rather vague atm. What I'd like is a clear number of how many terminations (by reason) happened within the select time frame. Would that be eligible for setting in stone?

**Comment by brancz** [comment]
I think the biggest problem about that is that it’s not a clear failure case, which is why it might be interesting at troubleshooting time but doesn’t make for a great alerting rule. As I said I think this still makes a good example query that we should still document.

**Comment by brancz** [comment]
I don’t really think that dashboard is a good fit as it’s about resources rather.
