### ISSUE TITLE
New dashboard workload by priorityClass

### ISSUE THREAD

**Issue by shaikatz** [kubernetes-monitoring/kubernetes-mixin#365]
I think it'll be cool the have a dashboard that shows counts of workloads by priority classes.
I would even add a table that shows the actual deployment and drop-down list that let you select the priority class that you see in the table.
It'll allow you to better manage the priority classes in the cluster.

WDYT?

**Comment by brancz** [comment]
Is there more time than a single query? If not then it’d recommend we maybe start a docs section: useful one off queries?
