### ISSUE TITLE
$__interval template doesn't work

### ISSUE THREAD

**Issue by povilasv** [kubernetes-monitoring/kubernetes-mixin#372]
Currently my change https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/357 broke dashboards 

I tried multiple different ways in grafana UI to fix it, by changing variable template to 'constant', 'text box' type with value `$__interval`, but it just doesn't render :/

I think there are 2 options:

1) We can get rid of grafana template and "hard code" `$__interval` into queries

I mean getting rid of this part:
```
    local intervalTemplate =
      template.new(
        name='interval',
        datasource='$datasource',
        query='$__interval',
        current='5m',
        hide=2,
        refresh=2,
        includeAll=false,
        sort=1
      ) + {
        auto: false,
        auto_count: 30,
        auto_min: '10s',
        skipUrlSync: false,
        type: 'interval',
        options: [
          {
            selected: true,
            text: '$__interval',
            value: '$__interval',
          },
        ],
      },
```

2) Don't use $__interval

What should we do?

**Comment by brancz** [comment]
Maybe grafana folks could chime in @beorn7 @gouthamve or maybe @roidelapluie has some insight.

**Comment by beorn7** [comment]
I'm actually not really a Grafana expert. We could loop in the real experts if needed.

But let's use our own ingenuity first.

My guess is that `$__interval` doesn't work with template variables. (Perhaps you would need some kind of two layers of variable expansion? But I honestly don't quite understand what you are trying to accomplish here.)

Different question: What's wrong with using $__interval in the queries directly? What are the circumstances where you want to use something else?

**Comment by brancz** [comment]
I think it was just that we had specific values previously and wanted to avoid creating work for us should we want to switch back again. If there’s nothing then I’m happy with using the variable directly though.

**Comment by beorn7** [comment]
I see.

I'd indeed recommend to go for `$__interval` always (with a reasonably setting for _min step_ to avoid that the `$__interval` becomes too short, something like four times the scrape interval).

This should be "almost" right in probably all the cases. For the related problem of getting "true" coverage, see https://github.com/grafana/grafana/issues/21417

**Comment by zhiqiangchine2x** [comment]
generated .json dashboards metrics are generated with $__interval as the range , instead of a numeric number, is this expected?

**Comment by kyrogue** [comment]
generated dashboards .json are having the $__interval placeholder, it should be a numeric instead. this is building from master branch.

**Comment by brancz** [comment]
@povilasv can you double check this?

**Comment by beorn7** [comment]
`$__interval` is a Grafana-specific thing. Only inside Grafana, it will be populated with a numeric value. Jsonnet has to render it as `$__interval`.

**Comment by povilasv** [comment]
My PR () just removed unused variable, don't see how it could break master.

I also tried to generate dashboards from master branch and everything is fine.

This is what get's generated:
```
               "targets": [
                  {
                     "expr": "(sum(irate(container_network_receive_bytes_total{cluster=\"$cluster\", namespace=~\"$namespace\"}[$__interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) mixin_pod_workload{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=\"$type\"}) by (workload))\n",
                     "format": "table",
                     "instant": true,
                     "intervalFactor": 2,
                     "legendFormat": "",
                     "refId": "A",
                     "step": 10
                  },
```

and it render fine in Grafana.

**Comment by kyrogue** [comment]
<img width="1469" alt="Screen Shot 2020-04-15 at 8 41 08 PM" src="https://user-images.githubusercontent.com/655464/79338512-053eb000-7f5a-11ea-8aec-37a1c2677ed3.png">
is there additional configuration required in Grafana for the internal variable $__interval to be rendered?

**Comment by povilasv** [comment]
What's the time range you are looking at and Prometheus scrape interval?

Try increasing the window to last 2 days? Does it render?

**Comment by kyrogue** [comment]
Ah, increasing Grafana time range to 24 hours worked, anything below does not render.
Thanks. 
I suppose this is because the range is too short and Prometheus does not have enough datapoints to render onto the graph panel?

**Comment by beorn7** [comment]
Yeah, you need to set a _Min step_ or _Min time interval_.

Shameless plug: I had planned to do a talk about exactly that at Grafanacon. With the conference being Corona-cancelled, there will be some kind of online version of that. See https://grafana.com/about/events/grafanacon/2020/ for more details in the close future.

**Comment by povilasv** [comment]
:+1: 

I'm closing this issue as it has been solved
