### ISSUE TITLE
kube-apiserver Grafana dashboard. ETCD cache graphs in Kubernetes >=v1.16

### ISSUE THREAD

**Issue by angelbarrera92** [kubernetes-monitoring/kubernetes-mixin#379]
**What happened?**

The grafana dashboard related to the kube-apiserver has some queries to prometheus (related to etcd) that was deprecated in Kubernetes 1.16.

**Did you expect to see some different?**

Maybe these graphs should be removed.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy this solution in a Kubernetes Cluster > 1.16

**Anything else we need to know?**:

https://github.com/kubernetes/kubernetes/issues/88803#issuecomment-594683394
https://github.com/kubernetes/kubernetes/pull/79520
https://github.com/coreos/kube-prometheus/issues/440#event-3137291784

**Comment by brancz** [comment]
cc @povilasv as the author of these do you maybe want to add this? :)

**Comment by povilasv** [comment]
I can take a look at that. But I think first we need to make a new release, as current state works fine 1.15. cc @brancz

**Comment by brancz** [comment]
Happy to have a release cut and then do this. You want to take care of it?

**Comment by povilasv** [comment]
I would but I think we need to first fix https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/394 as alerts are broken and we removed previous working alerts https://github.com/kubernetes-monitoring/kubernetes-mixin/commit/5325d944bfd5bb7fd4a84a86a7a49acd46356e89

**Comment by brancz** [comment]
Happy to wait for that. I don’t think we’re in a rush.

**Comment by brancz** [comment]
Actually I cut a release-0.4 branch, so we could move ahead with this. And the fix for the kube api alerts we can cherry-pick into the branch

**Comment by povilasv** [comment]
awesome :+1:

**Comment by povilasv** [comment]
@brancz quick question why 0.4 as previous one was https://github.com/kubernetes-monitoring/kubernetes-mixin/releases

Also could you make a release in github? :)

This one is not a blocker https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/394 as I tested it on 1.15  / 1.16 so we are fine.

**Comment by brancz** [comment]
Because of how `jb` works, it's most beneficial to just have release branches and people install head of those branches and bump the versions they want.

**Comment by povilasv** [comment]
:+1: I just personally like github releases as you can watch them + we can add a description describing which kubernetes version is release for.

![image](https://user-images.githubusercontent.com/22289110/80356488-34222380-8882-11ea-9a5c-6df44a90482a.png)

**Comment by brancz** [comment]
sounds good to me

**Comment by metalmatze** [comment]
Can we close this? :thinking:

**Comment by brancz** [comment]
I think the dashboards still have the etcd graphs, so those have yet to be removed.

**Comment by povilasv** [comment]
Yeah those graphs still need to be removed.
