### ISSUE TITLE
KubeletPodStartUpLatencyHigh error: many-to-many matching not allowed

### ISSUE THREAD

**Issue by deng47** [kubernetes-monitoring/kubernetes-mixin#392]
The expr of the KubeletPodStartUpLatencyHigh alter in alerts/kubelet.libsonnet seems to have an issue. Alertmanager failed evaluating it due to it causes a many-to-many matching. I am a beginner of PromQL, and when I changed the group_left to group_right, the expr seems working. Well, at least Alertmanager didn't complain. Could someone please check the expr? Thank you

k8s ver: 1.14.8
prometheus-operator:v0.30.1

Here is the expr 
`histogram_quantile(0.99, sum(rate(kubelet_pod_worker_duration_seconds_bucket{%(kubeletSelector)s}[5m])) by (instance, le)) * on(instance) group_left(node) kubelet_node_name  > 60`

Below is the error message from /var/log/message
`Apr  7 09:59:55 dev-promxy promxy[118082]: {"caller":"manager.go:512","err":"found duplicate series for the match group {instance=\"10.252.1.1:10250\"} on the right hand-side of the operation: [{__name__=\"kubelet_node_name\", endpoint=\"https-metrics\", instance=\"10.252.1.1:10250\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"kube-system\", node=\"ncn-w001\", service=\"kubelet\", sg=\"localhost_9090\"}, {__name__=\"kubelet_node_name\", endpoint=\"https-metrics\", instance=\"10.252.1.1:10250\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"kube-system\", node=\"ncn-w001\", service=\"prometheus-operator-kubelet\", sg=\"localhost_9090\"}];many-to-many matching not allowed: matching labels must be unique on one side","group":"kubelet.rules","level":"warn","msg":"Evaluating rule failed","rule":"record: node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile\nexpr: histogram_quantile(0.99, sum by(instance, le) (rate(kubelet_pleg_relist_duration_seconds_bucket[5m]))\n  * on(instance) group_left(node) kubelet_node_name{job=\"kubelet\",metrics_path=\"/metrics\"})\nlabels:\n  quantile: \"0.99\"\n","ts":"2020-04-07T16:59:55.973Z"}`

**Comment by brancz** [comment]
@povilasv any idea how we could improve this?

**Comment by povilasv** [comment]
I believe the issue is the join between `kubelet_pod_worker_duration_seconds_bucket` and `kubelet_node_name`  the join is on `instance` label.

@deng47 Can you send output of your `kubelet_node_name` and `histogram_quantile(0.99, sum(rate(kubelet_pod_worker_duration_seconds_bucket{%(kubeletSelector)s}[5m])) by (instance, le)) `

I believe somehow `kubelet_node_name` has multiple rows with same instance?

**Comment by brancz** [comment]
How about we just wrap the left side in `topk by(instance) (1, kubelet_node_name)`? That way we ensure there is only one. Question is however, how did that ever happen? Staleness?

**Comment by povilasv** [comment]
That's an option. I guess let's try to get the raw data first? As we have this join in a bunch of places https://github.com/kubernetes-monitoring/kubernetes-mixin/search?q=kubelet_node_name&unscoped_q=kubelet_node_name

**Comment by brancz** [comment]
@deng47 do you happen to have data around from when this happened? That might allow us to debug this further.

**Comment by deng47** [comment]
Hi, thank you for looking into my question. Below are some of my raw metrics of kubelet_pod_worker_duration_seconds_bucket and kubelet_node_name. Please let me know if that helps

```
# TYPE kubelet_pod_worker_duration_seconds_bucket untyped
kubelet_pod_worker_duration_seconds_bucket{endpoint="https-metrics",instance="10.252.1.5:10250",job="kubelet",le="0.5",metrics_path="/metrics",namespace="kube-system",node="ncn-w002",operation_type="update",service="kubelet",prometheus="monitoring/k8s",prometheus_replica="prometheus-k8s-0"} 12 1586392133030
kubelet_pod_worker_duration_seconds_bucket{endpoint="https-metrics",instance="10.252.1.1:10250",job="kubelet",le="+Inf",metrics_path="/metrics",namespace="kube-system",node="ncn-w001",operation_type="create",service="kubelet",prometheus="monitoring/k8s",prometheus_replica="prometheus-k8s-0"} 126240 1586392123783
kubelet_pod_worker_duration_seconds_bucket{endpoint="https-metrics",instance="10.252.1.1:10250",job="kubelet",le="+Inf",metrics_path="/metrics",namespace="kube-system",node="ncn-w001",operation_type="sync",service="prometheus-operator-kubelet",prometheus="monitoring/k8s",prometheus_replica="prometheus-k8s-0"} 299973 1586392135888
kubelet_pod_worker_duration_seconds_bucket{endpoint="https-metrics",instance="10.252.1.1:10250",job="kubelet",le="+Inf",metrics_path="/metrics",namespace="kube-system",node="ncn-w001",operation_type="sync",service="kubelet",prometheus="monitoring/k8s",prometheus_replica="prometheus-k8s-0"} 299972 1586392123783
kubelet_pod_worker_duration_seconds_bucket{endpoint="https-metrics",instance="10.252.1.1:10250",job="kubelet",le="+Inf",metrics_path="/metrics",namespace="kube-system",node="ncn-w001",operation_type="update",service="prometheus-operator-kubelet",prometheus="monitoring/k8s",prometheus_replica="prometheus-k8s-0"} 2287 1586392135888
kubelet_pod_worker_duration_seconds_bucket{endpoint="https-metrics",instance="10.252.1.1:10250",job="kubelet",le="+Inf",metrics_path="/metrics",namespace="kube-system",node="ncn-w001",operation_type="update",service="kubelet",prometheus="monitoring/k8s",prometheus_replica="prometheus-k8s-0"} 2287 1586392123783
kubelet_pod_worker_duration_seconds_bucket{endpoint="https-metrics",instance="10.252.1.1:10250",job="kubelet",le="0.005",metrics_path="/metrics",namespace="kube-system",node="ncn-w001",operation_type="create",service="prometheus-operator-kubelet",prometheus="monitoring/k8s",prometheus_replica="prometheus-k8s-0"} 0 1586392135888
kubelet_pod_worker_duration_seconds_bucket{endpoint="https-metrics",instance="10.252.1.1:10250",job="kubelet",le="0.005",metrics_path="/metrics",namespace="kube-system",node="ncn-w001",operation_type="create",service="kubelet",prometheus="monitoring/k8s",prometheus_replica="prometheus-k8s-0"} 0 1586392123783
kubelet_pod_worker_duration_seconds_bucket{endpoint="https-metrics",instance="10.252.1.1:10250",job="kubelet",le="0.005",metrics_path="/metrics",namespace="kube-system",node="ncn-w001",operation_type="sync",service="prometheus-operator-kubelet",prometheus="monitoring/k8s",prometheus_replica="prometheus-k8s-0"} 233871 1586392135888
```

```
# TYPE kubelet_node_name untyped
kubelet_node_name{endpoint="https-metrics",instance="10.252.1.1:10250",job="kubelet",metrics_path="/metrics",namespace="kube-system",node="ncn-w001",service="prometheus-operator-kubelet",prometheus="monitoring/k8s",prometheus_replica="prometheus-k8s-0"} 1 1586392135888
kubelet_node_name{endpoint="https-metrics",instance="10.252.1.1:10250",job="kubelet",metrics_path="/metrics",namespace="kube-system",node="ncn-w001",service="kubelet",prometheus="monitoring/k8s",prometheus_replica="prometheus-k8s-0"} 1 1586392123783
kubelet_node_name{endpoint="https-metrics",instance="10.252.1.5:10250",job="kubelet",metrics_path="/metrics",namespace="kube-system",node="ncn-w002",service="prometheus-operator-kubelet",prometheus="monitoring/k8s",prometheus_replica="prometheus-k8s-0"} 1 1586392151256
kubelet_node_name{endpoint="https-metrics",instance="10.252.1.5:10250",job="kubelet",metrics_path="/metrics",namespace="kube-system",node="ncn-w002",service="kubelet",prometheus="monitoring/k8s",prometheus_replica="prometheus-k8s-0"} 1 1586392133030
kubelet_node_name{endpoint="https-metrics",instance="10.252.1.6:10250",job="kubelet",metrics_path="/metrics",namespace="kube-system",node="ncn-w003",service="prometheus-operator-kubelet",prometheus="monitoring/k8s",prometheus_replica="prometheus-k8s-0"} 1 1586392151040
kubelet_node_name{endpoint="https-metrics",instance="10.252.1.6:10250",job="kubelet",metrics_path="/metrics",namespace="kube-system",node="ncn-w003",service="kubelet",prometheus="monitoring/k8s",prometheus_replica="prometheus-k8s-0"} 1 1586392141150
kubelet_node_name{endpoint="https-metrics",instance="10.252.1.7:10250",job="kubelet",metrics_path="/metrics",namespace="kube-system",node="ncn-m001",service="prometheus-operator-kubelet",prometheus="monitoring/k8s",prometheus_replica="prometheus-k8s-0"} 1 1586392132300
kubelet_node_name{endpoint="https-metrics",instance="10.252.1.7:10250",job="kubelet",metrics_path="/metrics",namespace="kube-system",node="ncn-m001",service="kubelet",prometheus="monitoring/k8s",prometheus_replica="prometheus-k8s-0"} 1 1586392139491
kubelet_node_name{endpoint="https-metrics",instance="10.252.1.8:10250",job="kubelet",metrics_path="/metrics",namespace="kube-system",node="ncn-m002",service="prometheus-operator-kubelet",prometheus="monitoring/k8s",prometheus_replica="prometheus-k8s-0"} 1 1586392139766
```

**Comment by brancz** [comment]
It looks like you are actively scraping the same kubelets multiple times. That doesn’t seem like it’s intentional, is it? Looks like you’re using the prometheus operator, do you have multiple instances of the prometheus operator running? Because the service used here looks like what the prometheus operator syncs but it only syncs one of those. It might be an old and new install of the prometheus operator.

**Comment by deng47** [comment]
We do have more than one Prometheus operators running in different namespaces, because serval teams in my organization want their own monitoring stack. Does it mean if I restrict the namespace, this expr would work? Sorry, I just don't have time to test it yet

**Comment by povilasv** [comment]
Thanks @deng47 that data helped a lot ;) The bug is that we didn't filter out correct kubelet when querying `kubelet_node_name`

**Comment by brancz** [comment]
That was definitely a bug but I'm not sure this will resolve @deng47's problem. Could you remove the `--kubelet-service` flag from all but 1 of your prometheus operator deployments, and delete all but that one service. Then you should be left with only one set of Kubelet's being discovered.

**Comment by m1o1** [comment]
For future people coming here, I found I had this issue after I tried to install the kube-prometheus-stack over top of the old prometheus-operator helm chart (just trying to keep the release name the same). It ended up creating two services (I believe the prometheus operator creates this) in the kube-system namespace for scraping the kubelet, and the ServiceMonitor was scraping both of them, so it was getting kubelet metrics twice.

**Comment by cortopy** [comment]
@m1o1 thanks for that!!! I had exactly the same issue. Removing the old service fixed it for me

**Comment by weisdd** [comment]
It'll happen even if you change release names while staying on the KPS chart. The service for kubelet seems to be abundant (look at labels and annotations): 
![image](https://user-images.githubusercontent.com/46579601/94014876-cfc5aa80-fdb4-11ea-8992-522736fe5f86.png)

**Comment by adipmeesse** [comment]
> For future people coming here, I found I had this issue after I tried to install the kube-prometheus-stack over top of the old prometheus-operator helm chart after the migration away from the stable helm repo (just trying to keep the release name the same). It ended up creating two services (I believe the prometheus operator creates this) in the kube-system namespace for scraping the kubelet, and both matched the selector of the ServiceMonitor so Prometheus was scraping both of them, so it was getting kubelet metrics twice.

Oh man. you helped me soo much. was searching for days why i had issues after switching from stable to the new stack chart. :+1:

**Comment by necipakca** [comment]
> For future people coming here, I found I had this issue after I tried to install the kube-prometheus-stack over top of the old prometheus-operator helm chart after the migration away from the stable helm repo (just trying to keep the release name the same). It ended up creating two services (I believe the prometheus operator creates this) in the kube-system namespace for scraping the kubelet, and both matched the selector of the ServiceMonitor so Prometheus was scraping both of them, so it was getting kubelet metrics twice.

You are the KING 👑
