### ISSUE TITLE
Adding rulebook_url also affects external alerts

### ISSUE THREAD

**Issue by serathius** [kubernetes-monitoring/kubernetes-mixin#40]
Automatic rulebook_url generation runs as mixin without any condition. 
So when vendoring `kubernetes-mixin`, my own alerts are also affected by this.

**Comment by tomwilkie** [comment]
Hi @serathius!  Thanks for the report.  Can confirm this is not the intention - I was under the impression the merge ordering would fix this but looks like we've got the same problem.  I'll give it some thought.

**Comment by serathius** [comment]
Your right, my lack of jsonnet knowledge here. Order is important here.
Maybe example in README would help?

**Comment by tomwilkie** [comment]
Sorry my comment was not clear: I was under the impression the merge ordering was important, but we have the same problem, and we're merging in the "right" order.  So it looks like merge ordering isn't important.  I need to do some more investigation.
