### ISSUE TITLE
PersistantVolume dashboard doesn't work with Azure file volumes

### ISSUE THREAD

**Issue by titilambert** [kubernetes-monitoring/kubernetes-mixin#404]
Hello,

When I select a volume with a storageclass azurefile the data of the space in the dashboard is wrong.
The root cause is the fact that the volume is mounted by several pods, so kubelet reports several times the same volume.
So the request
```
sum without(instance, node) (kubelet_volume_stats_capacity_bytes{cluster="$cluster", job="kubelet", namespace="$namespace", persistentvolumeclaim="$volume"})
```
make the sum of all the volume reported by kubelet.
This causes in the dashboard: `disk_capacity` = `nb_of_pods_using_this_volume` * `disk_capacity` (which is wrong and change depending on the number of run pods)

I changed the prom query, but I'm pretty sure there is some side effects for the "standard" disks ...

Hopefully, someone knows the perfect query which handle all types of storage classes

**Comment by jlohiya** [comment]
To be more concise, I observed that "nb_of_pods_using_this_volume" is more likely the number of nodes used by those pods using this volume instead of just pod counts.

**Comment by brancz** [comment]
If I understand correctly this has less to do with Azure file volumes but rather generally any ReadWriteMany type volumes?

**Comment by djsly** [comment]
Correct.

**Comment by brancz** [comment]
Kubelets aren't going to coordinate for this ever, so I think our best bet is to either do something like `max by(namespace, persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes)` or `topk(1, ...)` instead of `max`.

Alternatively, we might be able to join volume modes onto the metric and alert differently for ReadWriteOnce and ReadWriteMany volumes.

**Comment by djsly** [comment]
we looked at using topk(1) but I don't recall why we didn't use it in the end. 

I like the max by(persistentvolumeclaim) 

would be something like this ?

```
sum without(instance, node) (max by(namespace, persistentvolumeclaim) kubelet_volume_stats_capacity_bytes{cluster="$cluster", job="kubelet", namespace="$namespace", persistentvolumeclaim="$volume"}))
```

**Comment by brancz** [comment]
What does the dashboard actually show here? Aggregating volume capacity per node doesn't seem like a particularly useful thing in the first place.

The above query doesn't seem to make sense as the outer sum aggregates by instance and node label but the `max` function removes these dimensions as it only leaves namespace and persistentvolumeclaim through the `by` clause.

**Comment by cyclops8456** [comment]
@titilambert @djsly I ended up going down the topk route when hitting the same issue, different cluster platform (local cluster with Rook), but the same route cause.

**Comment by cyclops8456** [comment]
> Kubelets aren't going to coordinate for this ever, so I think our best bet is to either do something like `max by(namespace, persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes)` or `topk(1, ...)` instead of `max`.

@brancz As above, I just ended up using topk(1, ...), which seems to be working fine so far.  ReadWriteOnce PVCs will only return one result, and ReadWriteMany are displaying as expected now.
