### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by xkkker** [kubernetes-monitoring/kubernetes-mixin#418]
hi,I met a error when I run make command,any ideas?Thanks!
```
➜  kubernetes-mixin git:(master) ✗ make prometheus_alerts.yaml 
jsonnet -J vendor -S lib/alerts.jsonnet > prometheus_alerts.yaml
RUNTIME ERROR: Field does not exist: manifestYamlDoc
	lib/alerts.jsonnet:1:1-20	
Makefile:17: recipe for target 'prometheus_alerts.yaml' failed
make: *** [prometheus_alerts.yaml] Error 1	
```

**Comment by brancz** [comment]
What version of jsonnet do you have installed?

**Comment by xkkker** [comment]
oh, thanks for your reply!  I have read the issue before and notice that the error may caused because the version of jsonnet. My version of jsonnet is 0.9.5, I will upgrade it to 0.10.0+ to have a try.
Close this issue and thanks again!  @brancz
