### ISSUE TITLE
Alerts on inodes running out

### ISSUE THREAD

**Issue by MPV** [kubernetes-monitoring/kubernetes-mixin#426]
Hi,
It would be nice to have alerts on when PVCs are about to run out of free inodes. 

For example by using these metrics:
- `kubelet_volume_stats_inodes_free`
- `kubelet_volume_stats_inodes`

There are already other storage alerts, but they only look at bytes usage (or errors):
https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/8ede288c0e3f72513931e46445329ab084f79daa/alerts/storage_alerts.libsonnet

There's a dashboard that shows the inodes usage, but wouldn't it be nice to get alerted about it? 

<img width="945" alt="Skärmavbild 2020-05-20 kl  10 40 44" src="https://user-images.githubusercontent.com/62675/82425186-748e4f00-9a86-11ea-9717-237deedf8501.png">

**Comment by povilasv** [comment]
sounds reasonable :+1: feel free to do a PR

**Comment by skl** [comment]
Fixed by #761
