### ISSUE TITLE
Minimum intervals on dashboards result in `N/A` values

### ISSUE THREAD

**Issue by FrederikNS** [kubernetes-monitoring/kubernetes-mixin#429]
It seems that the semi-recent changes to selecting intervals in the actual Prometheus queries have resulted in a number of graphs being blank by default.

Most of the dashboards default to showing data from the last hour, and that results in an interval of 30 seconds. Unfortunately when Prometheus is set to it's default of scraping metrics every 20 seconds, that is too few datapoints to calculate a rate on.

The result is that "out-of-the-box" many of the dashboards look broken.

Kubernetes / Compute Resources / Cluster / CPU Utilization:
![Screenshot_2020-05-27 Kubernetes Compute Resources Cluster - Grafana](https://user-images.githubusercontent.com/181295/83112408-66fc4900-a0c6-11ea-8a45-b435f29d52cf.png)

Kubernetes / Compute Resources / Cluster / Current Network Usage:
![Screenshot_2020-05-27 Kubernetes Compute Resources Cluster - Grafana(1)](https://user-images.githubusercontent.com/181295/83112405-6663b280-a0c6-11ea-9919-62ba593f4740.png)

Kubernetes / Compute Resources / Namespace (Pods) / Current Network Usage:
![Screenshot_2020-05-27 Kubernetes Compute Resources Namespace (Pods) - Grafana](https://user-images.githubusercontent.com/181295/83112403-6663b280-a0c6-11ea-9d0d-afc506faf8a1.png)

Kubernetes / Compute Resources / Namespace (Workloads) / Current Network Usage:
![Screenshot_2020-05-27 Kubernetes Compute Resources Namespace (Workloads) - Grafana](https://user-images.githubusercontent.com/181295/83112398-6499ef00-a0c6-11ea-8499-c32d6fe55d76.png)

Kubernetes / Compute Resources / Workload / Current Network Usage:
![Screenshot_2020-05-27 Kubernetes Compute Resources Workload - Grafana](https://user-images.githubusercontent.com/181295/83112401-65cb1c00-a0c6-11ea-9632-8202a95d3e8c.png)

The solution is to introduce a high enough value in the "Min time interval" field (simply called "interval" in the JSON). In this case a value of 1 minute is enough for an actual value to show up. Here it is without the min interval:

![Screenshot_2020-05-28 Kubernetes Compute Resources Cluster - Grafana](https://user-images.githubusercontent.com/181295/83112471-7b404600-a0c6-11ea-8a4e-09a86d9af36d.png)

And here with the min interval:

![Screenshot_2020-05-28 Kubernetes Compute Resources Cluster - Grafana(1)](https://user-images.githubusercontent.com/181295/83112498-84311780-a0c6-11ea-85df-162e6e81844a.png)

**Comment by brancz** [comment]
I believe @beorn7 had mentioned as well that we need to set min interval in various places. @FrederikNS could you fix this? :)

**Comment by FrederikNS** [comment]
I'd love to, but I've never worked with jsonnet, so it will probably take a bit before I can supply a PR.

**Comment by jetersen** [comment]
@brancz if you could give a sample on how to update a single min time interval so we could better understand how to apply it to all the places where it is missing.

**Comment by brancz** [comment]
Unfortunately it doesn't seem to be documented in the json schema. There are docs [here](https://grafana.com/docs/grafana/latest/features/datasources/prometheus/) though. I would suggest creating a dummy panel and set that and inspect what the generated json looks like.

@beorn7 @gouthamve is there a place that I just didn't look? I couldn't find docs for the json schema for this feature. Might be something you wanna fix :)

**Comment by beorn7** [comment]
@brancz are you implying we know anything about Grafana? (o:

The weirdness I might be able to clear up is the following: The _min interval_ field is part of the whole panel (and as such not specific to the Prometheus data source). The _min step_ is per query, and it _is_ specific to Prometheus queries. Both have almost the same meaning, but the resolution setting (which is again specific to Prometheus queries) scales up _min interval_, but not _min step_ (for purely historical reasons, I assume).

Since this is programmatic anyway, I'd recommend to use _min step_, as then the user can change the resolution setting without blowing up the actually used min step.

For the schema: I would need to do exactly what @brancz said: In the UI, create a dashboard with a query with _min step_ set, and see where it ends up in the panel JSON.
