### ISSUE TITLE
Possible Error In Alert Query

### ISSUE THREAD

**Issue by sstubbs** [kubernetes-monitoring/kubernetes-mixin#432]
I have just installed this in a new single node cluster which has 24 cores and 64gb ram. It is only using about 2% resources however CPUThrottlingHigh, KubeCPUOvercommit and CPUThrottlingHigh are firing.

I have been looking at them and am not sure if these are correct.

```
sum(namespace:kube_pod_container_resource_requests_cpu_cores:sum)
  / sum(kube_node_status_allocatable_cpu_cores) > (count(kube_node_status_allocatable_cpu_cores)
  - 1) / count(kube_node_status_allocatable_cpu_cores)
```

Should the sum be compared with the sum rather than sum with count like it is currently? 

The same issue with this I think.

```
sum(namespace:kube_pod_container_resource_requests_memory_bytes:sum)
  / sum(kube_node_status_allocatable_memory_bytes) > (count(kube_node_status_allocatable_memory_bytes)
  - 1) / count(kube_node_status_allocatable_memory_bytes)
```

I am quite new to prometheus so perhaps I am mistaken but just thought I would post this issue in case.

I don't really understand what CPUThrottlingHigh is measuring so it's difficult for me to propose a fix for this.

**Comment by brancz** [comment]
They are very different. The overcommit alert essentially alerts when loss of a single node would cause pods to be unschedulable, which is always going to be the case for a single node cluster, so this alert is not particularly useful for a single node cluster.

CPU throttling however happens on a per container basis, this typically means you have under provisioned that containers cpu limits, or you have too many things fighting for the CPU available on the system.

Note that both of these alerts are severity warning, so they merely indicate that something might be wrong, but not necessarily is.

**Comment by sstubbs** [comment]
Ok thanks a lot.
