### ISSUE TITLE
KubeApiLatency alert firing even though not all conditions are matched

### ISSUE THREAD

**Issue by RiRa12621** [kubernetes-monitoring/kubernetes-mixin#434]
according to [this](https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/4626a8d0dd261dbefa91d9d60cf8bc8240bd053f/alerts/kube_apiserver.libsonnet#L64) the KubeApiLatencyHigh warning should only be firing if all conditions are met AND the latency is over 1s.
However we have seen this fire with

```
The API server has an abnormal latency of 0.05685404799999992 seconds for PUT namespaces.
```

## Expected behavior:
Alert fires if all conditions are matched

## Observed behavior:
Alert fires, ignoring the `>1s` condition

**Comment by metalmatze** [comment]
The alert has also been removed entirely going forward.
