### ISSUE TITLE
KubeQuotaExceeded fires even if quota is not exceeded

### ISSUE THREAD

**Issue by s-urbaniak** [kubernetes-monitoring/kubernetes-mixin#441]
From https://bugzilla.redhat.com/show_bug.cgi?id=1846707:

On OSD (OpenShift Dedicated) we create a ResourceQuota [1] for logging that is at 100% of what we allow allocating for logging PVCs.  The KubeQuotaExceeded alert fires if quota is at or above 90% allocated.  This means the alert is always firing.  The name of the alert implies quota is exceeded and we are getting concerned queries from customers regarding this alert firing in the cluster.  We don't think allocating less than 90% of the quota is the right answer and request the expr for this alert be adjusted.

We are tracking a workaround for our alerting [2] that will fire if quota is actually exceeded.  The expr would become:

```
kube_resourcequota{job="kube-state-metrics",namespace="(openshift-.*|kube-.*|default|logging)",type="used"} / ignoring(instance, job, type) (kube_resourcequota{job="kube-state-metrics",namespace="(openshift-.*|kube-.*|default|logging)",type="hard"} > 0) > 1 
```

/cc @jewzaam

**Comment by s-urbaniak** [comment]
cc @brancz @lilic @paulfantom @RiRa12621

**Comment by paulfantom** [comment]
This is alerting when usage is over 90% so we either should adjust alert name or fix the query to match name.

**Comment by metalmatze** [comment]
The updated query is alerting if the quota is above 100%? 
Could you explain a bit more in detail how the proposed solution works?

**Comment by jewzaam** [comment]
The proposed `expr` adjusts the alert to fire if quota is _exceeded_ which is what the alert name implies.  This is clearly a violation of allowed quota, which we would like to know about.  If quota is close to being consumed or consumed at 100% of allocated we don't care, this is acceptable.  If an alert is necessary when near quota limit that could be created but I recommend *not* alerting on platform namespaces.  As SRE I manage that platform and if I have quota it's well managed and I'm quite capable of adding additional alerts.

**Comment by metalmatze** [comment]
That makes sense, thanks for the in-depth explanation. :+1: 
I think updating this to 100% on here is fine from my side. 

Keep in mind, in this repository we are talking about any Kubernetes cluster and any namespace. It doesn't change anything, just wanted to highlight that there's nothing like a "platform namespace" here :)

**Comment by s-urbaniak** [comment]
@jewzaam feel free to contribute that change here. we can then pull downstream.

**Comment by brancz** [comment]
Does the alert still make sense then? How can quota be exceeded? By lowering quota after things have been created?

**Comment by RiRa12621** [comment]
In the scenario of OpenShift dedicated or any other fully managed service that could well happen.
In the given example someone would pay for logging, terminate their subscription for additional logging at some point and then their quota would be exceeded.

imho it still doesn't make a lot of sense and my proposal would be to rename it to `KubeQuotaFullyUsed` and reduced to info level and fire at 100%
The assumption is that it's still ok to use all your allocated quota but there should be an information about it, so in case for example deployments fail, you still have that info level and easily know what's wrong

**Comment by brancz** [comment]
@RiRa12621 's suggestion makes sense to me.

**Comment by RiRa12621** [comment]
Made a PR for this against master
https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/450

@jewzaam should keep in mind that we have to go through the whole backporting process if we want this to land in 4.3, 4.4 or 4.5
