### ISSUE TITLE
KubeletTooManyPods seems to take into account completed pods

### ISSUE THREAD

**Issue by paulfantom** [kubernetes-monitoring/kubernetes-mixin#442]
From https://bugzilla.redhat.com/show_bug.cgi?id=1846805

On OpenShift Dedicated the following alert is showing up:
KubeletTooManyPods alert “Kubelet 'worker.example.com' is running at 103.2% of its Pod capacity” while too many completed pods are still not deleted.

```
$ oc get PrometheusRule prometheus-k8s-rules -n openshift-monitoring -o yaml | less
    - alert: KubeletTooManyPods
      annotations:
        message: Kubelet '{{ $labels.node }}' is running at {{ $value | humanizePercentage
          }} of its Pod capacity.
      expr: |
        max(max(kubelet_running_pod_count{job="kubelet"}) by(instance) * on(instance) group_left(node) kubelet_node_name{job="kubelet"}) by(node) / max(kube_node_status_capacity_pods{job="kube-state-metrics"}) by(node) > 0.95
      for: 15m
      labels:
        severity: warning

# oc get pods -A -o wide | grep worker03 | wc -l
251

# oc get pods -A -o wide | grep worker03 | grep -v  'Completed|Running' | wc -l
256

# oc get pods -A -o wide | grep worker03 | grep -v  'Running' | wc -l
201

# oc describe node worker03
...
Capacity:
  cpu:                4
  ephemeral-storage:  314020844Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             32936388Ki
  pods:               250
Allocatable:
  cpu:                3500m
  ephemeral-storage:  289401609352
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             32321988Ki
  pods:               250
...
```

Actual results: Completed pods are taken into account where those does not impact on the resources used.

Expected results: Completed pods should not be taken into account.

Additional info: It does not affect to replicas scalability, it just seems confusing.

/cc @DHF-DaHernan

**Comment by DHF-DaHernan** [comment]
Thanks Paul. By the way, it is not only on Openshift Dedicated/RHMI, it is on all OCP 4 versions.

By the way, there is also a slightly related issue KubeletTooManyPods, but on K8s monitoring repo: https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/223

**Comment by paulfantom** [comment]
Seems like this is an issue in kubelet itself. Kubelet is reporting number of running pods with `kubelet_running_pod_count` which includes Completed pods.

A possible workaround is to use any container metric instead as seen in https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/443

**Comment by brancz** [comment]
hmm ... I feel this is rather something that should be fixed in Kubernetes, and not a workaround in the alerting rule

**Comment by metalmatze** [comment]
I'm happy to fix it with the workaround until most people are on a Kubernetes version that fixed the issue. Because the upstream Kubernetes issue has been opened, I'm happy to go ahead on our side.

**Comment by brancz** [comment]
In that case probably the best metrics to use for this would be the `kube_pod_info` metrics from kube-state-metrics.

**Comment by tyrken** [comment]
In my local fork of the downstream chart repo I'm using:
```
count((kube_pod_status_phase{phase="Running"} == 1) * on(pod) group_left(node) kube_pod_info) by(node) / max(kube_node_status_capacity_pods{job="kube-state-metrics"} != 1) by(node) > 0.95
```

**Comment by brancz** [comment]
That would work :)

**Comment by paulfantom** [comment]
```
count by(node) (
  (kube_pod_status_phase{phase="Running"} == 1) * on(pod,namespace,cluster) group_left(node) kube_pod_info
)
/ 
max by(node) (
  kube_node_status_capacity_pods{job="kube-state-metrics"} != 1
)
```

Seems to be working correctly. Do you want me to update #443 with that query?

**Comment by brancz** [comment]
It uses only kube-state-metrics metrics (including the node metric), so I think this is a safe one to use. Yes please update #443 with it and we can move forward I would say.
