### ISSUE TITLE
There is a rule triggering problem in Prometheus rules

### ISSUE THREAD

**Issue by guleng** [kubernetes-monitoring/kubernetes-mixin#448]
rules: 
expr: sum  by(resource, subresource, verb)(rate(apiserver_request_total{code=~"5..",job="apiserver"}[5m]))
  / sum by(resource, subresource, verb) (rate(apiserver_request_total{job="apiserver"}[5m])) > 0.05

This is the rule in the Prometheus rules file. I don't know what the indicator is. There is a trigger entry

API server is returning errors for 100% of requests for CONNECT services proxy.

What's the alarm of Kube API server?

**Comment by brancz** [comment]
I believe the rule in question was long updated to reflect this. Could you update?

**Comment by metalmatze** [comment]
The rule was updated in the meantime and for a couple of days even removed.
Please update your mixin to a newer version. 
If you cannot, feel free to send a PR, targeting a release branch, to fix it for the release you need it for.
