### ISSUE TITLE
Reduce severity on KubeNodeUnreachable

### ISSUE THREAD

**Issue by Duologic** [kubernetes-monitoring/kubernetes-mixin#459]
The severity currently comes up as `warning`, in an auto scaling environment this is not really a problem at all and actually fairly common. What do we think of lowering the severity to `info`?

https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/1d6014e6e9e158b90f99e88573b91e56a4171f66/alerts/kubelet.libsonnet#L25-L36

**Comment by paulfantom** [comment]
If you are using kuberentes autoscaler, it shouldn't fire at all. In cases where nodes are not autoscaled externally (like baremetal), `warning` severity seems valid.

**Comment by Duologic** [comment]
We're using preemptible nodes on GKE. So maybe we can ignore those cases too, will take stab at that tomorrow.

**Comment by Duologic** [comment]
I've found **cloud.google.com/impending-node-termination**, which I think can be ignored by the alert too.

I also have a more specific use case, we have a tailored process for rescheduling our workloads which also sets a NoSchedule taint and eventually removes the node. Would a config variable to expand the ignore list/query be a valid solution to cover this?
