### ISSUE TITLE
CPUThrottlingHigh alert, throttling of CPU in namespace kube-system for container mnzzz in pod mnzzz-daemonset-9gdkt

### ISSUE THREAD

**Issue by lianfulei** [kubernetes-monitoring/kubernetes-mixin#470]
alertname = CPUThrottlingHigh
message = 33.89% throttling of CPU in namespace kube-system for container mnzzz in pod mnzzz-daemonset-9gdkt.

why?

**Comment by lianfulei** [comment]
i have solve it

**Comment by Dr4il** [comment]
thx @lianfulei

**Comment by emmanue** [comment]
Hello @lianfulei can you share the solution to this error message? It will be helpful because we are facing the same issue.
