### ISSUE TITLE
Published tool which checks metrics in prometheus from Grafana Dashboard

### ISSUE THREAD

**Issue by witold-gren** [kubernetes-monitoring/kubernetes-mixin#478]
Hi everyone,

like we discussed in one PR https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/446 we finalise and public tool which check metrics from grafana dashboards and compare it with prometheus exist metrics.

All code can be found in GitHub repository: https://github.com/ContainerSolutions/prom-metrics-check. We also prepared very small docker image. If this tool is interesting for you, please mention about it in any place. 😀

**Comment by brancz** [comment]
I think this is really awesome! Where in the readme or other docs do you think it makes sense to mention it?

**Comment by witold-gren** [comment]
Maybe at the very bottom of the Readme page. Just add notes like:
```
# Note
You can use the external tool call **prom-metrics-check** created by Container Solutions to validate the created dashboards. This tool allows you to check if the metrics used in Grafana dashboards exist in the Prometheus instance. Please have a look at https://github.com/ContainerSolutions/prom-metrics-check.
```

**Comment by brancz** [comment]
Sounds good! You want to create the PR to add it? :)

**Comment by witold-gren** [comment]
Thanks, I did that 😀 https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/479
