### ISSUE TITLE
Alerts from prometheus-operator missing in runbook.md

### ISSUE THREAD

**Issue by rajalakshmi-v15** [kubernetes-monitoring/kubernetes-mixin#482]
Prometheus-operator helm chart ([link](https://github.com/helm/charts/tree/master/stable/prometheus-operator)) has two sets of rules: one for kubenetes version >= 1.14.0 ([link](https://github.com/helm/charts/tree/master/stable/prometheus-operator/templates/prometheus/rules-1.14)) and other for Kubernetes version < 1.14.0 ([link](https://github.com/helm/charts/tree/master/stable/prometheus-operator/templates/prometheus/rules)).

The runbook url points to runbook.md here in both the rule sets. The problem is that the rule set for kubetnetes >=1.14.0 contains newer rules and alerts which the current version of runbook.md does not have. It will be useful to include those rules here as well.

E.g: KubeQuotaExceeded, KubeHpaMaxedOut

**Comment by metalmatze** [comment]
Sounds good to me! Feel free to open PRs against the correct feature branches. 
Keep in mind that the alert name changed in June - KubeQuotaExceeded is now KubeQuotaFullyUsed.

**Comment by paulfantom** [comment]
Truth to be told, we currently have only 4 alerts (`KubeControllerManagerDown`, `KubeSchedulerDown`, `KubeJobCompletion`, and `KubeJobFailed`) in `runbook.md` which carry any information about how to proceed when alert fires. Everything else there is meaningless and confusing and probably should be removed.

That said I don't have anything against adding runbooks for other alerts as long as they have meaningful information on how to proceed with the issue presented by the alert.
