### ISSUE TITLE
Linux Dashboards are showing Windows pods

### ISSUE THREAD

**Issue by sachinmsft** [kubernetes-monitoring/kubernetes-mixin#483]
Hi,
Dashboard Kubernetes / Compute Resources / Pod is showing Windows pod also in drop down.
reason is that we are getting all the pods form the kube_pod_info

label_values(kube_pod_info{%(clusterLabel)s="$cluster", namespace="$namespace"}, pod)' % $._config.clusterLabel

I tried to solve it by using container_network_receive_packets_total metrics instead of kube_pod_info but this metrics does not have cluster information to filter the pods for cluster.

what is the correct way to fix this ?

**Comment by brancz** [comment]
The cluster label is intended to be applied as an external label, so they would actually be equivalent. I would suggest to use a memory or cpu metric just to make it whatever the first metric is that is used in the first panel but no strong opinion.

**Comment by sachinmsft** [comment]
Hi @brancz , Is cluster label applied to all the metrics. or to just kube_pod_info ?

**Comment by brancz** [comment]
External labels are applied to any metric in the Prometheus server.
