### ISSUE TITLE
Dashboards for Windows Nodes

### ISSUE THREAD

**Issue by selina-cui** [kubernetes-monitoring/kubernetes-mixin#497]
After run 'make dashboards_out',  I got these json files in dashboards_out folder, which one is the dashboard for windows nodes?

apiserver.json				
k8s-resources-cluster.json		
k8s-resources-pod.json			
kubelet.json				
persistentvolumesusage.json		
scheduler.json
cluster-total.json			
k8s-resources-namespace.json		
k8s-resources-workload.json		
namespace-by-pod.json			
pod-total.json				
statefulset.json
controller-manager.json			
k8s-resources-node.json			
k8s-resources-workloads-namespace.json	
namespace-by-workload.json		
proxy.json				
workload-total.json

**Comment by brancz** [comment]
You need to opt in to create the windows dashboards, they are not included by default.

**Comment by selina-cui** [comment]
Could you please provide more details about generating windows dashboard json file?

**Comment by brancz** [comment]
They are not part of https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/dashboards/dashboards.libsonnet so you just append them, something like:

```jsonnet
local kubernetes = import "kubernetes-mixin/mixin.libsonnet";

kubernetes +
(import "kubernetes-mixin/dashboards/windows.libsonnet")
```

**Comment by selina-cui** [comment]
> They are not part of https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/dashboards/dashboards.libsonnet so you just append them, something like:
> 
> ```jsonnet
> local kubernetes = import "kubernetes-mixin/mixin.libsonnet";
> 
> kubernetes +
> (import "kubernetes-mixin/dashboards/windows.libsonnet")
> ```

Thanks for your reply. I can build the five windows related dashboard after import windows.libsonnet.  But the dashboard is empty, I have installed windows node exporter in each worker node. And in prometheus,  I can see the metrics.
<img width="1383" alt="Screen Shot 2020-09-14 at 1 43 46 PM" src="https://user-images.githubusercontent.com/8787455/93047983-5d581a80-f690-11ea-9210-7a5f866b099f.png">

**Comment by brancz** [comment]
@sachinmsft could you help out here? (I believe you initially contributed these windows dashboards right?)

**Comment by sachinmsft** [comment]
Sure @brancz ,

@selina-cui , Can you please provide the details for below points.
1)  Have you imported Prometheus rules for Windows ? If not then you need to do that.
2) Can you please rename job to job=wmi-exporter https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/config.libsonnet#L32
3) Can you provide the couple of metrics from Prometheus.

**Comment by selina-cui** [comment]
Hi Sachin,

I have imported "windows.node.rules" and "windows.pod.rules", and most of  rules are in OK state. But some rules show the following errors:
`Error executing query: found duplicate series for the match group {namespace="kube-system"} on the right hand-side of the operation: [{__name__="windows_container_available", container_id="docker://7c135277c2eefd11a72e37733e6bb04d170ac81bce2a8705c3a08639d41fb015", endpoint="http-metrics", instance="192.168.113.5:9182", job="wmi-exporter", namespace="kube-system", node="dc2ece59-bc83-4ad2-a33b-32c22b7ebbf6", service="wmi-exporter"}, {__name__="windows_container_available", container_id="docker://326482b6b8a7f1bb52a964479fbf4a6d24dce73dd4a349e7ebb9b752ee3770b7", endpoint="http-metrics", instance="192.168.113.5:9182", job="wmi-exporter", namespace="kube-system", node="dc2ece59-bc83-4ad2-a33b-32c22b7ebbf6", service="wmi-exporter"}];many-to-many matching not allowed: matching labels must be unique on one side`

For the job name, do you mean the target name in Prometheus?
<img width="1784" alt="Screen Shot 2020-09-15 at 4 11 25 PM" src="https://user-images.githubusercontent.com/8787455/93185197-b054cf00-f76f-11ea-8635-8eb89bb48afd.png">

And here are the metrics from one windows node [metrics.txt](https://github.com/kubernetes-monitoring/kubernetes-mixin/files/5223483/metrics.txt)

Thanks,
Selina

**Comment by sachinmsft** [comment]
Seems like metrics have been renamed in latest version of wmi-exporter.
e.g. wmi_memory_available_bytes has been renamed to windows_memory_available_bytes.

I will send the PR to fix this in rules and dashboards.

**Comment by sachinmsft** [comment]
sent this PR https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/503

**Comment by selina-cui** [comment]
@sachinmsft Thanks for the quick fix. The five windows dashboards can display. The only problem is some data missing in cluster dashboard. Could you please take a look at it?
<img width="1723" alt="Screen Shot 2020-09-18 at 10 28 19 PM" src="https://user-images.githubusercontent.com/8787455/93611262-abf31500-fa00-11ea-80fb-15dee4fe49e2.png">

**Comment by sachinmsft** [comment]
@selina-cui The reason for this is that your windows pods does not have  CPU request, CPU limit, memory request and memory limit configured.

Note: I have sent one more PR https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/504 because in last PR I messed up 2 rules. you should import these rules/dashboards again.

**Comment by selina-cui** [comment]
@sachinmsft thanks a lot.
