### ISSUE TITLE
missing cluster label in network-usage dashboard

### ISSUE THREAD

**Issue by herveleclerc** [kubernetes-monitoring/kubernetes-mixin#516]
There is no `%(clusterLabel)s="$cluster"` in queries for network-usage dashboard.

When dashboards are generated in multi-cluster env  don't give correct graph.

**Comment by herveleclerc** [comment]
oops duplicate with  #325 ...
have you advanced on the subject ?

**Comment by brancz** [comment]
I don't think anyone is actively working on this.
