### ISSUE TITLE
Providing a toggle on/off for the KubeletTooManyPods alert

### ISSUE THREAD

**Issue by blame19** [kubernetes-monitoring/kubernetes-mixin#529]
The KubeletTooManyPods from alerts/kubelet.libsonnet is not always useful. 

For example, in our current setup we have a prometheus stack on AKS cluster with autoscaler enabled. The scheduling mechanism tries to fill up each node with as many pods as possible and a new node is issued when there are no available nodes in the nodepool. In this setting, the KubeletTooManyPods isn't providing an useful information and shouldn't be a warning (maybe a severity info).

Would it be possible to have a toggle? We'd like to be able to toggle the alert on and off through a variable in the prometheus helm chart.

**Comment by brancz** [comment]
I think moving it to being an info alert sounds good to me. Maybe we can even rename it to communicate a different urgency. I agree that arguably kubelets having many pods is actually a good thing, much like using resources (that we pay cloud providers for) efficiently.
