### ISSUE TITLE
Too many samples (still)

### ISSUE THREAD

**Issue by intrand** [kubernetes-monitoring/kubernetes-mixin#541]
I see PR #537 adjusted some apiserver sample ranges to reduce how many samples are loaded into prometheus during rule eval to prevent it from choking. We applied this update and saw a drastic reduction in failed evaluations. Thank you!

There are some other apiserver records/expressions that use a 30d sample which weren't updated with this PR and we're still choking on those.

Is there a reason these weren't updated? Is someone willing to open a PR to address those, as well?

Thanks for your hard work (everyone). This project has gotten our monitoring off the ground, so to speak, way faster than having to write this all by hand.

**Comment by brancz** [comment]
@metalmatze did we miss something here?

**Comment by paulfantom** [comment]
I did a quick `grep 30d -R .` in repo and don't see any results. @intrand can you give examples of rules which you have and are evaluated over 30d period?

**Comment by intrand** [comment]
Hmm. We're technically using kube-prometheus, which pulls this repo in. Maybe there's some modification in that project. I'll take a look in just a few minutes.

Attached is our jsonnet. Only some fields (like hostnames) have been doctored - strings are still strings, ints are still ints, etc.

We build our jsonnet like so:
```
git clone --branch v0.6.0 https://github.com/prometheus-operator/kube-prometheus.git
cd kube-prometheus
docker pull quay.io/coreos/jsonnet-ci
docker run --rm -v "${PWD}":"${PWD}" --workdir "${PWD}" quay.io/coreos/jsonnet-ci jb update

cp ../our.jsonnet .
cp -r ../grafana-dashboards .
docker run --rm -v "${PWD}":"${PWD}" --workdir "${PWD}" quay.io/coreos/jsonnet-ci ./build.sh our.jsonnet
```
[our.jsonnet.txt](https://github.com/kubernetes-monitoring/kubernetes-mixin/files/5845280/our.jsonnet.txt)

**Comment by intrand** [comment]
Here is a (very) truncated version of the prometheus-rules.yaml that's produced through the procedure outlined above. I've cut out anything that *isn't* 30d.

Please notice `apiserver_request_total:increase30d` and `apiserver_request:availability30d` are present (along with the expressions that each span the 30d time period)
[prometheus-rules.yaml.txt](https://github.com/kubernetes-monitoring/kubernetes-mixin/files/5845308/prometheus-rules.yaml.txt)

**Comment by intrand** [comment]
Alright, I've looked through the other repository and it looks like those rules are present, but only in [a sample YAML manifest](https://github.com/prometheus-operator/kube-prometheus/search?q=30d). I don't *think* that gets pulled in during this process, but I can certainly experiment with that tomorrow at work. My understand is it pulls this project in at "compile" time and spits out YAMLs that their operator can understand.

I will definitely get back to you tomorrow. Thanks for the quick responses!

**Comment by paulfantom** [comment]
You're right, we didn't update this dependency in kube-prometheus. I've created a PR to do this, however, bear in mind that we are now refactoring that project and it might have some incompatibilities with previous versions.

**Comment by intrand** [comment]
I apologise for opening the issue with the wrong project. Would we prefer to close this here and track it in a new issue in kube-prometheus? I'm willing to go open a new issue.

Thank you very much for the assistance and quick responses. I'm always impressed by and grateful for open source projects with active contributors/community members.

**Comment by paulfantom** [comment]
Yes, I think we can close it now. If there are more problems regarding this, don't hesitate to open an issue in kube-prometheus :)
