### ISSUE TITLE
Rules for HPA conditions 

### ISSUE THREAD

**Issue by mcristina422** [kubernetes-monitoring/kubernetes-mixin#551]
There could be more rules for Horizontal Pod Autoscaler. The HPA status conditions include useful information that could be warnings or alerts.

Specifically one example is when `ScalingActive` is `false` for an extended period of time. We typically see this as a misconfiguration of external metrics. If it is in this state for an extended period of time there needs to be intervention.

Additionally the ScalingLimited condition could be used t ehanace/replace the [KubeHpaMaxedOut](https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/ff9354e31f5fed45da32a2b460794a518409dcb2/alerts/apps_alerts.libsonnet#L305) rule

Ref: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#appendix-horizontal-pod-autoscaler-status-conditions

**Comment by metalmatze** [comment]
In a perfect world we would want  these to live with the HPA itself. I can see how it fits here perfectly too so I'm happy to have them here and willing to merge them! :blush: 
Keep the PRs coming! :+1:

**Comment by brancz** [comment]
I think this is the perfect place, considering we already have deployment, statefulset, daemonset, etc. alerts. Looking forward to the alerts! :)
