### ISSUE TITLE
CPU / Memory Requests / Limits goes above 100%

### ISSUE THREAD

**Issue by shubhambhattar** [kubernetes-monitoring/kubernetes-mixin#554]
https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/e6c423c05a2c50adf4bba77f50f317663a03e09a/dashboards/resources/cluster.libsonnet#L104

The CPU Requests, CPU Limits, Memory Requests and Memory Limits in **Kubernetes / Compute Resources / Cluster** goes above 100%.

We found that if there are a few pods which are in states like `Evicted`, `OOMKilled`, `Completed`, etc. CPU Requests, CPU Limits, Memory Requests, Memory Limits for those were also counted.

Ideally we should only count for pods which are in `Running` State, right?

**Comment by brancz** [comment]
I believe the CPU part was just solved by https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/552 ? Could you validate that?

**Comment by shubhambhattar** [comment]
@brancz Yes, for CPU Requests it looks okay. I verified the result by running the following query which makes CPU Requests 0 for pods which aren't in `Running` state:

```
sum(sum by (pod) (kube_pod_container_resource_requests_cpu_cores) * on (pod) kube_pod_status_phase{phase="Running"})
```

And the final sum matches with:

```
sum(namespace:kube_pod_container_resource_requests_cpu_cores:sum)
```

**Comment by shubhambhattar** [comment]
@brancz I've made similar changes for Memory Requests Commitment in this PR: https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/555

Validated with query:
```
sum(sum by (pod) (kube_pod_container_resource_requests_memory_bytes) * on (pod) kube_pod_status_phase{phase="Running"})
```

**Comment by paulfantom** [comment]
Closing this as both PRs (for CPU and for memory) are merged now.
