### ISSUE TITLE
Allow scoping alerts to certain namespaces

### ISSUE THREAD

**Issue by brancz** [kubernetes-monitoring/kubernetes-mixin#56]
We have two use cases for scoping alerts to certain namespaces:

1) There is a Prometheus server that collects all cluster wide metrics from kubelets, cAdvisor, and kube-state-metrics, for a cluster that has multiple independent users/tenants, therefore it adds significant cognitive overhead for SREs responsible offering the cluster as a service to their users throughout the entire pipeline (Prometheus alerts page, Alerts fired against Alertmanager, list of alerts in Alertmanager), when all they care about are the alerts for the cluster components and infrastructure.

2) Different users/tenants may have different configurations of the "application" specific alerts of this repository.

@metalmatze @tomwilkie Do you think this is something we should optionally allow defining? I think the default behavior should continue to be what we have today.

**Comment by metalmatze** [comment]
Yes. We should allow people to split these things. I think that's something that people from Loodse are interested in too, right @pkavajin?

How would you like to split these on a jsonnet level, @brancz?

**Comment by brancz** [comment]
I think there are two ways we can go about this, either split it on the entire mixin level and then have the "main" (current) mixin import the namespaced + non-namespaced alerts and dashboards or just on the alerts in the same way (I think this would be sufficient as the dashboards are harder to categorize in namespace/non-namespaced). The latter makes default configs a bit harder though.
