### ISSUE TITLE
/readyz /livez /healthz requests in apiserver_request_duration

### ISSUE THREAD

**Issue by metalmatze** [kubernetes-monitoring/kubernetes-mixin#560]
In the last week I got an increase in _KubeAPIErrorBudgetBurn_ for the 3d duration, so very slow error budget burn.
Digging into the burnrates I could see that it wasn't an elevated error rate but rather slow requests on the APIServer.

![Screenshot from 2021-03-03 17-52-04](https://user-images.githubusercontent.com/872251/109841367-4494ee80-7c49-11eb-89ab-4b6cafb21841.png)

This query then confirmed that there are indeed quite slow requests which should be below 1s.

Now I'm wondering should we exclude `subresource!~"/(readyz|livez|healthz)"` as this seems internal to the apiserver rather than about the APIServer itself.

Additionally, does any know if something changed in the APIServer recently that could explain this? :thinking: 

This is on a Scaleway Kubernetes v1.19.7 cluster.

**Comment by brancz** [comment]
I think we should exclude readyz, livez, healthz. However, I think you should also open an issue on kubernetes/kubernetes and ping sig-apimachinery to try and explain this, because 1s for these endpoints seems rather high to me as well, but it could have a perfectly good explanation (which would be great if it was documented somewhere if this is expected).

**Comment by metalmatze** [comment]
While opening the issue at kubernetes/kubernetes and looking at the data again, I saw that these health endpoints where always there. It's just that they got significantly worse in the last couple of days. 

![Screenshot from 2021-03-05 17-22-56](https://user-images.githubusercontent.com/872251/110143391-7fc52800-7dd7-11eb-95de-bab39f1417b0.png)

I'm assuming that this is due to some changes made by my cloud provider, most likely throttling CPU of my apiserver more?
For now I don't think this is something we should open with kubernetes/kuberentes. It's still worth exploring if we should exclude these in the future.

Maybe @sttts knows or knows someone who can help figure out. That would be amazing!

**Comment by metalmatze** [comment]
Looking at `rate(apiserver_request_duration_seconds_bucket{job="apiserver",le="1",scope=~"resource|",verb=~"LIST|GET"}[6h])` one fix would be to add `subresource!~"/(healthz|livez|readyz)"`. The alternative would be to figure out why we have `scope=~"resource|"` which matches empty scope. The problematic subresouces don't have those.
Basically this would already fix it:
```diff
-scope=~"resource|"
+scope=~"resource"
```

**Comment by metalmatze** [comment]
Found a comment by myself in #403 
> Additionally, I also had to fix the `scope=~"resource|"` for Kubernetes 1.18+, as the `scope="resource"` doesn't seem to exist anymore.

Doesn't seem to be true though :thinking:
