### ISSUE TITLE
Regression on multiple dashboards

### ISSUE THREAD

**Issue by rdagnelie** [kubernetes-monitoring/kubernetes-mixin#570]
Hi,

I think we have a regression from MR #567 

All dashboards which have been modified by this MR look like this:

![2021-03-22_17-46](https://user-images.githubusercontent.com/58891894/112026592-a5bc2d80-8b36-11eb-9f27-c2c924c2d528.png)

**Comment by anfouque** [comment]
I can confirm this issue. Before, each network panels were in a raw, now they are all outside and compacted.

**Comment by paulfantom** [comment]
cc @jan--f

**Comment by jan--f** [comment]
I suppose we should set a width on the panels. Any objections against each panel taking the full width?

**Comment by paulfantom** [comment]
We can have either all panels take a full row or have multiple rows with 1-2 panels in each. I don't have preference and both lgtm.
