### ISSUE TITLE
Broken panels when setting `showMultiCluster: true`

### ISSUE THREAD

**Issue by ArthurSens** [kubernetes-monitoring/kubernetes-mixin#578]
When setting `showMultiCluster: true` I've noticed that some dashboards are deployed with broken panels:

Compute Resources / Multi-Cluster:
![image](https://user-images.githubusercontent.com/24193764/113343147-cf7b0e80-9305-11eb-9b1b-4ddbde2967a5.png)

Compute Resources / Cluster:
![image](https://user-images.githubusercontent.com/24193764/113343201-e3bf0b80-9305-11eb-86cc-0e2b53b99c93.png)

---
Also, the `Multi-Cluster` dashboard queries are all filtered by `cluster=$cluster` while there is no variable called `cluster`

**Comment by ArthurSens** [comment]
The panels broke on commit 2785a9f0addd11c77c82a0c3e8580b556621049d, just a small mistake with missing brakets 🙂

**Comment by rdagnelie** [comment]
already corrected in PR #573

**Comment by ArthurSens** [comment]
Ah nice, I've searched and somehow missed this PR. Apologies :)
