### ISSUE TITLE
KubeCPUOvercommit constantly flapping

### ISSUE THREAD

**Issue by syst0m** [kubernetes-monitoring/kubernetes-mixin#589]
On a 4 node cluster, The `KubeCPUOvercommit` alert keeps constantly firing and resolving itself.

Looking at the alert query, I'm not entirely sure how you arrived at the logic for it.
In my particular use case, the right side of the comparison equals to `0.75` on a 4 node cluster -`((count(kube_node_status_allocatable_cpu_cores) - 1) / count(kube_node_status_allocatable_cpu_cores)`.
This appears to be counting the total number of nodes and not the total number of CPUs.
The left side of the equation - `sum(namespace:kube_pod_container_resource_requests_cpu_cores:sum) / sum(kube_node_status_allocatable_cpu_cores)` usually calculates to ~0.68 in my example.

Since the alert resolves itself on it's own, I'm not really sure what the supposed remediation should be?
Also, since cluster-autoscaler is deployed, I don't really see how the cluster would not tolerate a node failure,
which is suggested by the alert description?

**Comment by syst0m** [comment]
After additional investigation, it appears the alert always fires when the `cluster-autoscaler` scales down an unused node.
In this case, when total number of nodes goes from 4->3, the same ratio of summed workload over the summed allocatable CPU cores will trigger an alert.
I'm still unsure as to why this would be an issue on a cluster with `cluster-autoscaler` deployed, since if any of the nodes were to go down the autoscaler would automatically provision new nodes.

**Comment by guyguy333** [comment]
I'm having the same issue and I agree.

I think a better expression would be to consider that there is at least 1 free node available in autoscaler range.

**Comment by paulfantom** [comment]
I am closing the issue as it should be fixed with https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/646. If you still see the problem, please reopen.
