### ISSUE TITLE
Cannot deploy using ksonnet

### ISSUE THREAD

**Issue by sanderaernouts** [kubernetes-monitoring/kubernetes-mixin#59]
I followed the steps in `README.md` to create an application and default application. I then installed `prometheus-ksonnet` running `jb install github.com/kausalco/public/prometheus-ksonnet` and made the suggested changes to `main.jsonnet` but when I run `ks apply default` I get this error:
```
ERROR find objects: C:\tmp\use-monitoring\vendor/prometheus-ksonnet/lib/nginx.libsonnet:26:21 Text block not terminated with |||

      'nginx.conf': |||
```

I'm using the latest release of ksonnet I found on github (0.12.0)
I'm running this from a windows machine.

**Comment by metalmatze** [comment]
I think this is a bug in prometheus-ksonnet by kausal and not this repository.
