### ISSUE TITLE
Customizing Kuberentes-mixin Alerts and Rules with Operator (kube prometheus stack)

### ISSUE THREAD

**Issue by samuelgautier** [kubernetes-monitoring/kubernetes-mixin#600]
Hi all,
I woud like to be able to customize some of the rules and alerts coming from this mixin. I've installed prometheus/alertmanager/grafana using the kube-prometheus-stack operator. This topic seems to be in your TODO list according to the README.
For example, i would like to be able to change the CPUThrottlingHigh threshold of the default alert rule. How can i proceed ?
Any help would be appreciated.
Thanks in advance.
Regards

Infos : 
kube-prometheus-stack installed with helm 3 on K8S 1.18 chart version 14.3.0 stack version 0.46.0

**Comment by paulfantom** [comment]
This is an omission in README. We recommend using [kube-prometheus](https://github.com/prometheus-operator/kube-prometheus) project in which all customizations listed in [README.md#customising-the-mixin](
 https://github.com/kubernetes-monitoring/kubernetes-mixin#customising-the-mixin) can be applied. kube-prometheus project exposes all those customizations as [`$.values.kubernetesControlPlane.mixin._config`](https://github.com/prometheus-operator/kube-prometheus/blob/main/jsonnet/kube-prometheus/main.libsonnet#L113)

**Comment by shinebayar-g** [comment]
Looking for a same answer. I guess helm chart users have no way to modify the underlying resources because it's written in whole another language jsonnet and the compiled into yaml files.

**Comment by paulfantom** [comment]
> I guess helm chart users have no way to modify the underlying resources 

Correct. Helm chart users need to swap whole alert expressions.

> it's written in whole another language jsonnet and then compiled into yaml files

Lack of customizations in yaml and helm is why mixins and [kube-prometheus](https://github.com/prometheus-operator/kube-prometheus/) are written in jsonnet and not pure YAML :)

> Helm chart just pulls that yaml files.

This is helm issue, not kubernetes-mixin project.
