### ISSUE TITLE
Some graphs can't differentiate between nodes with the same IP in multi-cluster setup.

### ISSUE THREAD

**Issue by jppitout** [kubernetes-monitoring/kubernetes-mixin#605]
Hi,

We are running kubernetes-mixin release-0.4

We have multiple TKGi (PKS) clusters in different Azure virtual networks. The kubernetes nodes in different virtual networks have the same IPs, this is by design to simplify orchestration/automation and to ensure that clusters are, as far as possible, identical. 

Each of these clusters has a federated Prometheus feeding a central Prometheus, the problem is that even in multi-cluster mode kubernetes-mixin dashboards use order "by instance" which isn't enough to differentiate between them. This causes Grafana to omit duplicate IPs but by adding order by cluster e.g. "by﻿ ﻿(﻿instance﻿, ﻿name﻿, ﻿cluster﻿)" Grafana can differentiate between nodes with the same IPs.

![image](https://user-images.githubusercontent.com/61308549/117456993-18e3fc80-af49-11eb-8a96-ce5ea5fd946e.png)

Is there a way this ^^^ can be customised kubernetes-mixin so that we don't need to manually create/edit these graphs?

**Comment by jppitout** [comment]
Another good example is the Scheduler dashboard which is only grouped by instance even though multi-cluster is configured:
![image](https://user-images.githubusercontent.com/61308549/117483696-51460380-af66-11eb-9844-1adb45d69bee.png)

**Comment by paulfantom** [comment]
Great catch! We are open to PRs with a fix for this. 

It looks like you need to modify:
1) controller-manager dashboard queries in https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/dashboards/controller-manager.libsonnet
2) scheduler dashboard queries in https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/dashboards/scheduler.libsonnet

**Comment by saumyabakshi** [comment]
Hi, I've added a PR with the suggested changes!
