### ISSUE TITLE
Memory usage removed from Pod dashboard without any reason, why?

### ISSUE THREAD

**Issue by luarx** [kubernetes-monitoring/kubernetes-mixin#609]
Hi everyone,

I am just curious to know why memory cache usage was removed because **it could be useful** when debugging some pod memory usage.

Here was introduced for the first time:
https://github.com/kubernetes-monitoring/kubernetes-mixin/commit/7e38d71f7b858d048357be700720142ffbf51d7d#diff-27b8f025088ff00a3b5f1a233a8ca75c96d32982ebc9292f1eda9b3fd6a01ab4R39
Example:
![image](https://user-images.githubusercontent.com/22997139/119466320-cb3b0280-bd44-11eb-98f5-05140b1365dc.png)

And, as I can see, in this commit **was removed because the dashboard was duplicated, but this metric was not included in the duplicated one** :(:
https://github.com/kubernetes-monitoring/kubernetes-mixin/commit/f7e7c5f6fd0a7f3c1753623a47d1e08c7ad84954#diff-27b8f025088ff00a3b5f1a233a8ca75c96d32982ebc9292f1eda9b3fd6a01ab4L41
Example:
![image](https://user-images.githubusercontent.com/22997139/119466452-ead22b00-bd44-11eb-968f-e813dd653702.png)

From my point of view, it is a metric that it is useful to know how the memory is used.
So my question is: **was it removed on purpose?** 

Thanks in advance!

**Comment by luarx** [comment]
cc. @brancz, @omerlh and @dghubble as they talked about the PR that included that commit here https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/362

**Comment by paulfantom** [comment]
That was an omission and it would be good to bring those metrics back. Do you want to give it a try and create a PR?
