### ISSUE TITLE
Variable discovery of `cluster` and `namespace` is inefficient

### ISSUE THREAD

**Issue by mhulscher** [kubernetes-monitoring/kubernetes-mixin#610]
When using the grafana dashboards in multi-cluster mode, the discovery of values of the variables `cluster` and `namespace` is very inefficient.

For example, the `k8s-resources-pod.json` dashboard uses this query to discover the clusters `label_values(kube_pod_info, cluster)`. (Most dashboards use a variant of this query.) This means that when I am looking at a single container, pod, deploy, namespace, node, or whatever resource, Grafana is going to query thanos/cortex/whatever for **all** the pods in **all** my clusters, just to get the list of clusters. In our case, this can return hundreds of thousands of timeseries of `kube_pod_info` to figure out that there are 11 clusters.

The same holds true for discovery of the `namespace` variable. The same dashboard uses this to discover namespace: `label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)`. This requests all pods in the entire cluster, which again can be thousands. Whereas the number of namespaces is significantly less.

For our own purposes I modified the dashboards post-render. I replaced discovery of clusters and namespaces in all dashboards like so:

```
# cluster
label_values(kube_namespace_created{namespace=\"kube-system\"}, cluster)

# namespace
label_values(kube_namespace_created{cluster=\"$cluster\"}, namespace)
```

This has decreased the load on our thanos and has sped-up the loading of dashboards significantly. From minutes to seconds.

Would you consider a PR that modifies the dashboard templates as such? One downside I can see is that dashboards will show all clusters and all namespaces, regardless of whether the timeseries relevant to the current dashboard are present there. So selecting a cluster/namespace might show empty graphs.

**Comment by paulfantom** [comment]
Although I don't like to have empty dashboards I think this is a reasonable tradeoff for increased performance in larger installations.

**Comment by mhulscher** [comment]
@paulfantom thanks for the reply. Do you think we should update the queries for all dashboards? Or should we perhaps only use these queries when `showMultiCluster` is set to true? I am unfamiliar with jsonnet so I'm not sure if conditionals are a thing.

**Comment by paulfantom** [comment]
It would be good to test how those new queries behave in a single cluster scenario and if there are no empty dashboards, I say let's not use conditionals. Otherwise it would make sense to use them.

Yes conditionals are a thing: https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/dashboards/apiserver.libsonnet#L228 :)

**Comment by mhulscher** [comment]
I can already guarantee that there will be empty dashboards in a new cluster. New clusters come with the following namespaces by default, which will have no workloads running in them: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#viewing-namespaces
