### ISSUE TITLE
KubeAPIErrorBudgetBurn Alert Reason

### ISSUE THREAD

**Issue by d-m** [kubernetes-monitoring/kubernetes-mixin#615]
Hello all,

I was hoping that someone might be able to help me with understanding why the KubeAPIErrorBudgetBurn alert (long: 3d, short 6h) was firing.

I reviewed the API Server dashboard and noticed that there were large spikes for an entry with no resource label:

<img width="730" alt="Screen Shot 2021-05-28 at 10 16 13 PM" src="https://user-images.githubusercontent.com/2354832/120055255-cf944380-c002-11eb-8d33-d8452a752c8c.png">

The dashboard uses the query `cluster_quantile:apiserver_request_duration_seconds:histogram_quantile{verb="read"}`.

I also read through https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/464 and the very helpful [runbook](https://github.com/prometheus-operator/kube-prometheus/wiki/KubeAPIErrorBudgetBurn) mentioned in a comment in that ticket. The only example query in the runbook that returned any results was the resource scoped slow read request query but it didn't have a resource name, either:

<img width="683" alt="Screen Shot 2021-05-28 at 10 22 54 PM" src="https://user-images.githubusercontent.com/2354832/120055349-81cc0b00-c003-11eb-93d5-81957548305d.png">

Any suggestions for next steps would be appreciated.

Thanks.

**Comment by metalmatze** [comment]
You should be able to figure out the slow resource be removing the `sum()` to only have the rate which won't aggregate anymore.

**Comment by paulfantom** [comment]
We might want to link to https://github.com/prometheus-operator/kube-prometheus/wiki/KubeAPIErrorBudgetBurn somewhere and/or improve it.

**Comment by mihail-velikov** [comment]
Update:
It seems that my suspicion was incorrect. We updated all ingress endpoints to the latest version of the api but the problem persists.
Additionally I tried enabling the profiling of the api-server but not much more information was added in the logs about the slow requests.

**Comment by povilasv** [comment]
One approach to use tracing if you would run newer k8s version -> https://kubernetes.io/blog/2021/09/03/api-server-tracing/
