### ISSUE TITLE
HPA metrics compatibility with kube-state-metrics v2.0+

### ISSUE THREAD

**Issue by avivgold098** [kubernetes-monitoring/kubernetes-mixin#621]
The [apps hpa](https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/alerts/apps_alerts.libsonnet)  alerts are incompatible with `kube-state-metrics` v2.0.0+.
* `kube-state-metrics` renamed the the `HPA` metrics names, from `kube_hpa_*` to `kube_horizontalpodautoscaler_*`
* `release-0.8` and `master` are effected

https://github.com/kubernetes/kube-state-metrics/pull/1003

**Comment by avivgold098** [comment]
Would like to assist with the solution once the issue is accepted by the maintainers

**Comment by brancz** [comment]
Thank you for reporting! Please feel free to contribute a fix :)
