### ISSUE TITLE
KubeDaemonSetRolloutStuck may fire while progress is being made

### ISSUE THREAD

**Issue by simonpasquier** [kubernetes-monitoring/kubernetes-mixin#625]
Copying description from https://bugzilla.redhat.com/show_bug.cgi?id=1943667#c0 

>KubeDaemonSetRolloutStuck is firing during a large number of small cluster upgrades because it can't really differentiate between:
>
>1. stuck on a set of nodes
>2. an efficient and orderly rollout where we smoothly and rapidly upgrade all the nodes, but the same number of pods are always unavailable
>
>The alert KubeDaemonSetRolloutStuck looks at the number of scheduled/ready/unavailable pods and also looks for changes.  However, in small/medium clusters a smoothly progressing rollout will continuously have a few pods down:
>
>6 nodes, 2 updated at a time (1 master / 1 worker):
>
> 
> Master A / Worker A get drained
> Master A / Worker A get rebooted
> 2 Pods in DS are down, daemonset looks like scheduled: 6, ready/available: 4
> Master A / Worker A start up again, pods go ready
> Master B / Worker B get drained fast and rebooted within 30-45s
> 2 Pods in DS are down, daemonset looks like scheduled: 6, ready/available: 4
> ...
> Last upgrade completes, daemonset looks like scheduled: 6, ready/available: 6

As a stop-gap, we've extended the `for` clause to `30m` for the alert shipped in OpenShift but it might be good to investigate whether the alert can be improved to differentiate between "daemonset pod stuck on node X" and "daemonset pods being rolled out at a steady rate".

**Comment by brancz** [comment]
hmm interesting, is this with the latest version of the alert that includes the[ total amount updated increasing](https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/0c768c338b4a1188a4c50a5dd67da3cca0d97db1/alerts/apps_alerts.libsonnet#L179-L181)?

**Comment by paulfantom** [comment]
Yes, this happening on latest version of the alert.

**Comment by brancz** [comment]
I would have expected that the `kube_daemonset_updated_number_scheduled` metric should have changed since other nodes are making progress, do we understand why this didn't help?
