### ISSUE TITLE
Using 'pps' instead of 'Bps' as the unit of "Rate of Packets" panels under pod's dashboard

### ISSUE THREAD

**Issue by just1900** [kubernetes-monitoring/kubernetes-mixin#631]
Panels related to "Rate of Packets" are using 'Bps' as the unit currently, is that more accurate to use 'pps', indicates the packets/sec?

Related jsonnet below:

https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/e0dc3563dcbf2e54e0ffe8e83f3f51b237ef33be/dashboards/resources/pod.libsonnet#L270-L298

**Comment by paulfantom** [comment]
Yes, it makes more sense to use `pps`. Would you mind creating a PR?
