### ISSUE TITLE
[Question] Why are burn rate SLOs set as they are? 

### ISSUE THREAD

**Issue by MattJeanes** [kubernetes-monitoring/kubernetes-mixin#643]
Hello, we're currently experiencing KubeAPIErrorBudgetBurn alerts on our cluster but after some investigation and drilling down the alert and rules we've landed on [these SLOs](https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/rules/kube_apiserver.libsonnet#L25-L75) defined in the apiserver_request:burnrate rules which as far as I can tell show the following SLOs in terms of API server response times:

0.1 seconds for a resource read (GET|LIST)
0.5 seconds for a namespace read
5 seconds for a cluster read
1 second for a write (POST|PUT|PATCH|DELETE)

These contradict quite heavily with the [official SLOs](https://github.com/kubernetes/community/blob/master/sig-scalability/slos/slos.md#steady-state-slisslos) which show:

1 second for a resource read
5 seconds for a namespace read
30 seconds for a cluster read
1 second for a write

Unless I'm misunderstanding this (which admittedly is quite likely!) why is there such a difference between the kubernetes-mixin SLOs and the official ones?

**Comment by brancz** [comment]
cc @metalmatze

**Comment by metalmatze** [comment]
I think you're right @MattJeanes, these numbers are wrong and probably came from testing things... :confounded: 
In December I've actually seem to have fixed them while making the buckets configurable in a branch that I've never sent as a PR... :confused: Super sorry about that...

**Comment by MattJeanes** [comment]
I thought I must have been misunderstanding something since I couldn't see anyone else raising this - maybe everyone else just has really good uptime! 😄

That is great news though, hopefully this will make the `KubeAPIErrorBudgetBurn` stop firing on my cluster. No need to apologise at all mate, it's all good 🙂
