### ISSUE TITLE
Port-forward requests mess up API success rate

### ISSUE THREAD

**Issue by gmaiztegi** [kubernetes-monitoring/kubernetes-mixin#652]
We are currently having KubeAPIErrorBudgetBurn alerts in our cluster, and our Grafana chart show pretty clearly that there are many read requests targeting pods that run for exactly 60 seconds.

![Screenshot 2021-08-02 at 15 51 14](https://user-images.githubusercontent.com/753673/127872510-1e904b75-2d53-4f26-95f8-e3108d95999f.png)

After some digging and running this query `cluster_quantile:apiserver_request_duration_seconds:histogram_quantile{resource="pods", cluster=""}` we see that it is the portforward request that takes longer than what the SLO specifies.

![Screenshot 2021-08-02 at 15 39 40](https://user-images.githubusercontent.com/753673/127871527-a38d7e05-309f-4eae-9202-18fd87aefdb2.png)

But it feels lik port-forwards should be long running operations by definition.

As port-forwards are long running operations, it seems to me that it makes sense to take them out when calculating the aggregated success rate for the API resources.

**Comment by skl** [comment]
Fixed by #740
