### ISSUE TITLE
Dashboards panels can be migrated to "Table panels"

### ISSUE THREAD

**Issue by philipgough** [kubernetes-monitoring/kubernetes-mixin#656]
Grafana [revamped their table panels](https://grafana.com/blog/2020/04/28/grafana-7.0-sneak-peek-new-table-panel-for-dashboards/) between 6.x and 7.x

Some of the dashboards that ship with mixin give the option to migrate to this latest panel. 
<img width="1917" alt="Screenshot 2021-08-04 at 14 31 18" src="https://user-images.githubusercontent.com/5781491/128195617-058c0960-bdae-4102-a579-48acaac43cd5.png">

Taking the `Cluster` dashboard as an example, without doing this migration step in the UI, the behaviour of some features that worked in 6.x are broken in 7.x

When I try top export a table as CSV, `CPU Quota` in this example I get the following output in 7.x:
<img width="976" alt="Screenshot 2021-08-04 at 14 25 56" src="https://user-images.githubusercontent.com/5781491/128196424-2a9fa76f-d298-4c96-9a06-49a71669e610.png">

After manually running the migration step, I get the following output ready to be exported:
<img width="984" alt="Screenshot 2021-08-04 at 14 31 57" src="https://user-images.githubusercontent.com/5781491/128196601-4d819262-97fa-4f09-9695-532d4bb2b262.png">

This matches the old behaviour when the dashboard was included in Grafana 6.x.

**Comment by skl** [comment]
Migration has been completed.
