### ISSUE TITLE
Slow requests with subresource="proxy" should not be included in apiserver burnrate

### ISSUE THREAD

**Issue by scoof** [kubernetes-monitoring/kubernetes-mixin#671]
I believe that slow proxy requests should be excluded from the burnrate of apiserver, since it has no relevance to the performance of the actual apiserver.
In our case, we're seeing alerts on burnrate because the node metrics endpoint is slow, but the apiserver is performing as it should.
Would an acceptable solution be to exclude slow requests to proxies from counting towards the burnrate?

**Comment by povilasv** [comment]
The SLOs are defined in https://github.com/kubernetes/community/blob/master/sig-scalability/slos/api_call_latency.md and https://github.com/kubernetes/community/blob/master/sig-scalability/slos/slos.md#steady-state-slisslos 

I think the best approach would be to discuss this issue in the k8s repository.

**Comment by scoof** [comment]
closing in favor of https://github.com/kubernetes/community/issues/6050
