### ISSUE TITLE
Tighten up prometheus queries to avoid collisions

### ISSUE THREAD

**Issue by james-callahan** [kubernetes-monitoring/kubernetes-mixin#673]
I was puzzled as to why looking at our dashboards, the resource requests/limits were double what I expected.
Deconstructing the queries, I saw that e.g. https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/7120319a5b5c45e8dd2e79f0ad60e2284c6d6f1b/dashboards/resources/cluster.libsonnet#L164 was unintentionally summing in metrics from kubecost (https://github.com/kubecost/cost-model/blob/068510c25953fc176d85c0ac756f31579f78a67d/pkg/metrics/podmetrics.go#L62)

One possible solution would be to add `job="kube-state-metrics"` to the query.

**Comment by povilasv** [comment]
yup, feel free to add the jobselector label
