### ISSUE TITLE
Use grafana dashboard linter

### ISSUE THREAD

**Issue by arajkumar** [kubernetes-monitoring/kubernetes-mixin#713]
A tool from grafana[1] may be useful to detect issues in the dashboard definition generated by kubernetes-mixin.

[1] https://github.com/grafana/dashboard-linter

**Comment by arajkumar** [comment]
I would like to explore on this. @paulfantom WDYT?

**Comment by arajkumar** [comment]
I agree that the tool is still in very early stage.

**Comment by paulfantom** [comment]
Go for it :+1:

**Comment by povilasv** [comment]
:+1:
