### ISSUE TITLE
Where does the `$cluster` variable come from?

### ISSUE THREAD

**Issue by zachfi** [kubernetes-monitoring/kubernetes-mixin#727]
Good day,

I see a few tickets about this, but none seem to apply to me.  I've got a single cluster and am trying to use this mixin, but the $cluster variable is empty due to the `kube_pod_info` metric missing the label for cluster.  How do I add that label to my cluster so that the dashboards will work?  Is that in the prometheus scrape configs, or the global config, or something that is in `$._config` of this mixin?

**Comment by paulfantom** [comment]
Take a look at https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/config.libsonnet#L84

**Comment by dimm0** [comment]
Is there a more general example? Which section does it go to?
