### ISSUE TITLE
Alert KubeContainerWaiting is using the wrong expression

### ISSUE THREAD

**Issue by zshrine** [kubernetes-monitoring/kubernetes-mixin#728]
We have been having the alert firing with the description **Pod kube-system/kube-state-metrics-7575857457-8p2xj container kube-state-metrics has been in waiting state for longer than 1 hour.** but the pod kube-state-metrics-7575857457-8p2xj has been running with no problems. After checking, it was actually another pod in the exported_pod label. The kube-state-metrics pod is just the one serving the metrics.

I think it should use the expression `sum by(exported_namespace, exported_pod, exported_container)` ?

**Comment by paulfantom** [comment]
kube-state-metrics scrape job should use `honor_labels: true` to prevent `exported_*` labels from appearing and override `namespace`, `pod`, and `container` labels. Take a look at https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/kubeStateMetrics-serviceMonitor.yaml#L13-L23. With such an approach existing rules work as expected.

**Comment by zshrine** [comment]
Hi, thank you for the reply. Yes, you are right. We did not set `honor_lables: true` hence it did not work as expected. Thank you for the assistance.
