### ISSUE TITLE
advise on KubeCPUOvercommit

### ISSUE THREAD

**Issue by eugenetaranov** [kubernetes-monitoring/kubernetes-mixin#731]
Hello,

could someone please elaborate the usage of cpu requests in KubeCPUOvercommit alarm, not limits ? 
Here is the link to the related query: https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/9821d07e94e9a9916575a234fb699ae3331fa939/alerts/resource_alerts.libsonnet#L28

According to kubernetes documentation, the pod is scheduled only if all requests can be satisfied, seems like real overcommit may occur only with limits, when some pods use more resources then they originally requested.

Thanks!

**Comment by eyenx** [comment]
The description is quite handy here:

> Cluster has overcommitted CPU resource requests for Pods by {{ $value }} CPU shares and cannot tolerate node failure.',

Meaning, it calculates if there are more CPU Resources requested from all pods then all the Allocatable CPU minus the biggest node. 

This alert predicts your pods won't run if a Node is down. It has nothing to do with limits as far as I understand it, it's just about being able to schedule all nodes if one of the nodes is down (example: during updating).
