### ISSUE TITLE
Requirements for mixin

### ISSUE THREAD

**Issue by gtorre** [kubernetes-monitoring/kubernetes-mixin#734]
👋 Hello!

I've been working on setting up monitoring in our cluster and I came across this project. It isn't very clear to me what the requirements/prerequisites are. I see that there are references to `kube-state-metrics` in this [matrix](https://github.com/kubernetes-monitoring/kubernetes-mixin#releases). I also see references to other things like `kubernetes-node-exporter` in the [Customising the Mixin section](https://github.com/kubernetes-monitoring/kubernetes-mixin#customising-the-mixin). However, and this could just be me, there is no clear requirement or prerequisite section for what components need to be running for the alerts/rules/dashboards generated in this project to work correctly.

For example, if I import the `Kubernetes / API server` Grafana dashboard, one of the metrics used is `apiserver_request`. Where does this metric get exposed? The API server directly? Or is there a specific exporter that scrapes the API to generate the metric?

If the former is true, I've setup prometheus to scrape the API server /metrics endpoint and that metric does not exist:
![image](https://user-images.githubusercontent.com/5504515/150848216-a9a96ff6-6aa1-4fa0-8165-d9ae6668495b.png)

Any help or insight would be greatly appreciated! Also, I'd be happy to open a PR (if the information doesn't exist somewhere already) once I've gathered all of the pertinent information.

FWIW, we're currently running k8s v1.21.5 via kops 1.22.3

Thanks,
Gennaro

**Comment by paulfantom** [comment]
`apiserver_request_aborts_total` comes directly from apiserver `/metrics` endpoint ([apiserver code for reference](https://github.com/kubernetes/apiserver/blob/master/pkg/endpoints/metrics/metrics.go#L227-L234)).

Minimal requirements are as follows:
- node_exporter
- kube-state-metrics
- kubelet metrics
- apiserver metrics

It is also recommended to have metrics from:
- CoreDNS
- kube-scheduler
- kube-controller-manager

Related to this, there is an ongoing effort to document which particular metrics are necessary to allow everything to be running smoothly (cc @arajkumar). More in https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/620

**Comment by gtorre** [comment]
Thanks for getting back to me @paulfantom 

The metric in question was actually `apiserver_request`. Perhaps one of the dashboards I looked at is outdated? I don't see the metric in the code.

Thanks for clarifying what the minimal requirements are!

**Comment by paulfantom** [comment]
The metric `apiserver_request` is not referenced anywhere in the kubernetes-mixin project. We do have however the following ones (notice they are wildcard as the last bits vary depending on particular SLO window):
- `apiserver_request:availability.*`
- `apiserver_request:burnrate.*`
And those are coming from recording rules shipped by the project - https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/e43fe7c1ecf3d4a5f9ac752b039780922e04341a/rules/kube_apiserver.libsonnet#L26-L108.

**Comment by gtorre** [comment]
Thanks for clearing that up for me @paulfantom !
