### ISSUE TITLE
Job alert uses often-absent metric

### ISSUE THREAD

**Issue by bboreham** [kubernetes-monitoring/kubernetes-mixin#747]
This code does not achieve what it wants to:
https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/c76b9378b86d28bd617d94a57c72b4770efed510/alerts/apps_alerts.libsonnet#L238-L241

It is subtracting `kube_job_status_succeeded` from `kube_job_spec_completions`.

`kube_job_spec_completions` reads from the spec, but [in the spec](https://kubernetes.io/docs/concepts/workloads/controllers/job/#parallel-jobs) that field is optional.
For jobs which leave it unset (which inside Kubernetes defaults it to 1), the metric does not exist, and the alert does not fire.

I guess one could argue that `kube-state-metrics` should export the 1 value for jobs that don't explicitly set it, but I don't want increased cardinality.

Instead, the alert could do something like `kube_job_info{...} OR kube_job_spec_completions{...}`, since `kube_job_info` has a value of 1.

**Comment by arajkumar** [comment]
Great timing, we are already tacking a similar problem here in https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/746

**Comment by paulfantom** [comment]
Fixed in https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/746
