### ISSUE TITLE
Added feature: Grafana unified alerting

### ISSUE THREAD

**Issue by agermain** [kubernetes-monitoring/kubernetes-mixin#763]
Hi all! 

We use kubernetes-mixin and were wondering if it'd be possible to somehow (easily/programmatically) migrate these useful alerts to Grafana-managed alerts, which seems to have a Prometheus-like abstraction of alerts. At first glanceit seems the JSON  structure returned for Prometheus-managed vs Grafana-managed is not equivalent so I think programmatic translation would be non-trivial.

Any ideas, or if there's any existing tools that can help us achieve such result, are welcome.

Ref: [Grafana unified alerting](https://grafana.com/docs/grafana/latest/alerting/unified-alerting/), and its [API specification](https://editor.swagger.io/?url=https://raw.githubusercontent.com/grafana/grafana/main/pkg/services/ngalert/api/tooling/post.json).

**Comment by tingeltangelthomas** [comment]
+1
