### ISSUE TITLE
change all grafana dashboards timezone to default

### ISSUE THREAD

**Issue by jolson490** [kubernetes-monitoring/kubernetes-mixin#77]
Have all the dashboards use the local browser default timezone - not UTC.

Resolves the comments on the following issue about setting the timezone for the grafana web ui: https://github.com/coreos/prometheus-operator/issues/1807

**Comment by jolson490** [comment]
Note that I found the following:

https://github.com/grafana/grafonnet-lib/blob/master/grafonnet/dashboard.libsonnet
```
timezone='browser',
...
timezone: timezone,
```

https://github.com/grafana/jsonnet-libs/blob/master/grafana-builder/grafana.libsonnet
```
timezone: 'utc',
```

cc @brancz

**Comment by brancz** [comment]
I think we should use the "default" setting for timezone, which uses whatever is configured globally in Grafana (instead of the browsers default timezone or UTC hardcoded into the dashboards).

**Comment by jolson490** [comment]
And with kube-prometheus can you please tell me if there's a way to specify/change the globally configured timezone in grafana?
I'm trying to understand all the pieces that would be required for the ultimate result of being able to have dashboards use the local timezone.

**Comment by brancz** [comment]
I think that's more a question for Grafana people to answer, the jsonnet Grafana files allow setting arbitrary config, but I don't know how/where to set it in the config.
