### ISSUE TITLE
KubeMemoryOvercommit counts evicted pods

### ISSUE THREAD

**Issue by perek** [kubernetes-monitoring/kubernetes-mixin#781]
We recently had the  KubeMemoryOvercommit alert fire on a cluster of ours that was not overcommitted, it was firing because there were a few evicted pods that pushed it over the limit configured. Since evicted pods will never start should be ignore failed pods in this alert? If not should we possibly update the alert to mention that evicted pods are possible to cause this alert?

**Comment by rexagod** [comment]
I can take this up!
