### ISSUE TITLE
Causes an issue when showMultiCluster and multiple prometheus replicas

### ISSUE THREAD

**Issue by rgarcia89** [kubernetes-monitoring/kubernetes-mixin#788]
When setting `showMultiCluster` to `true` this board is showing multiple values in the first panel in case that you have more then one replica of the prometheus-server running. It probably would make sense to place an avg function around the query.

![image](https://user-images.githubusercontent.com/4134730/187880959-2239fa55-e7ce-4467-9e5f-86b08e230f98.png)

https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/1ddc6f6f739cc9fe4b8ac6a0fbb23cb09fe53bc3/dashboards/resources/cluster.libsonnet#L143

**Comment by rgarcia89** [comment]
Same counts for this query
https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/1ddc6f6f739cc9fe4b8ac6a0fbb23cb09fe53bc3/dashboards/resources/multi-cluster.libsonnet#L25

**Comment by antonblr** [comment]
https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/834 is related to this.
