### ISSUE TITLE
Migrate apiserver request latency metric to `apiserver_request_sli_duration_seconds`

### ISSUE THREAD

**Issue by dgrisonnet** [kubernetes-monitoring/kubernetes-mixin#809]
In Kubernetes 1.26 we renamed the `apiserver_request_slo_duration_seconds` metric to `apiserver_request_sli_duration_seconds`: https://github.com/kubernetes/kubernetes/pull/112679 and we are looking at removing the `_slo_` metric in 1.27. As such, the mixins should be updated to use the new metric.

/cc @metalmatze

**Comment by metalmatze** [comment]
I wonder if a recording rule could be helpful for the migration. I remember similar things from node-exporter migrations.

**Comment by dgrisonnet** [comment]
Yeah, that could definitely help since it would allow using whichever metric is available.

**Comment by dgrisonnet** [comment]
Thinking about it again, having a recording rule to select one the metrics will introduce these potential problems:
- without label aggregation, the evaluation will take a lot of time considering the sheer amount of metrics
- metrics won't be as fresh as they used to be since their freshness will now depend on the evaluation period

**Comment by dgrisonnet** [comment]
I believe you fixed it in https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/874 no?
