### ISSUE TITLE
KubeAPIDown not working as intended if targets a set of clusters

### ISSUE THREAD

**Issue by thunko** [kubernetes-monitoring/kubernetes-mixin#825]
hi,

I get the following rule when generating prometheus alerts for kubeapi:
```
- "alert": "KubeAPIDown"
    "annotations":
      "description": "KubeAPI has disappeared from Prometheus target discovery."
      "runbook_url": "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubeapidown"
      "summary": "Target disappeared from Prometheus target discovery."
    "expr": |
      absent(up{job="kube-apiserver"} == 1)
    "for": "15m"
    "labels":
      "severity": "critical"
```
The issue that I'm running into is, that my prometheus instance reads data for several clusters, meaning if I add this rule, it doesn't work as intended because the alert will not trigger as long as there is *any* KubeAPI that is up.  
I could create a rule for each cluster, but I'd like to avoid hard-coding.

Have you run into a similar situation and what would you suggest for such use case ?
Thank you,

**Comment by zoftdev** [comment]
+1 best approch is think is compare with history. if apiserver disappear then raise alert.
