### ISSUE TITLE
Modifying Existing Alerts 

### ISSUE THREAD

**Issue by jdbaldry** [kubernetes-monitoring/kubernetes-mixin#9]
Adding new alerts is nice and simple by extending the `prometheus_alerts+:: ` structure, but as it is a list, adding labels or annotations to existing alerts isn't. 

For example wanting to modify the message annotation to link to playbooks or something. Speaking to Tom, if this was a dictionary rather than a list, this would then become possible.

**Comment by brancz** [comment]
My thinking is that for things like that it's best to just have documentation on how to enrich alerts, as there can be arbitrary modifications people may want to do with arbitrary selections (as in not just by alert name possibly).

Just pseudocode, but what I'm thinking is:

```
local runbooks {
  "<alertname>": <runbook-link>,
}

local modifiedAlertGroups = std.mapWithKey(function(group) {
  std.mapWithKey(function(rule) {
    rule + { annotations+: { runbook: runbooks[rule.alert] }
  }, group.rules)
}, kubernetesMixins.prometheusAlerts.groups)
```

**Comment by tomwilkie** [comment]
I'm doing something similar with this code, @jdbaldry:

```
  prometheusAlerts+:: {
    local overrides = $.alertOverrides,
    groups: std.map(function(group)
      group {
        rules: std.map(function(rule)
          rule +
          if std.objectHas(overrides, rule.alert)
          then overrides[rule.alert]
          else {}, super.rules),
      }, super.groups),
  },
```

**Comment by tomwilkie** [comment]
A util function to help here is being added in #26
