### ISSUE TITLE
Changes in grafanaDashboardIDs map doesn't take effect

### ISSUE THREAD

**Issue by oik741** [kubernetes-monitoring/kubernetes-mixin#936]
Override values in the grafanaDashboardIDs map have no effect on the UIDs of dashboards.

I have several clusters with different versions, and loading multiple versions of dashboards causes a conflict of UIDs due to their non-uniqueness, which breaks the linking. This could be resolved by overriding the UIDs, but this functionality does not work.

**Comment by oik741** [comment]
@bonddim @skl @rgeyer could you take a look please?)

**Comment by rgeyer** [comment]
These look good to me, however. While @skl and I recently contributed to the dashboards we are not maintainers or approvers so we can't execute the workflows or merge the PRs.

I don't expect that the maintainers would merge into existing release branches, so I suspect only #937 would be considered/merged, but I suppose we'll see. :)
